// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsSentiResult.proto

package com.gw.ps.pbbean;

public final class PbNewsSentiment {
  private PbNewsSentiment() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NewsSentimentOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required int64 newsCode = 1;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    boolean hasNewsCode();
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    long getNewsCode();

    // required int32 sentiment = 2;
    /**
     * <code>required int32 sentiment = 2;</code>
     *
     * <pre>
     *新闻情感识别结果，-1表示负面，1表示正面，0不确定
     * </pre>
     */
    boolean hasSentiment();
    /**
     * <code>required int32 sentiment = 2;</code>
     *
     * <pre>
     *新闻情感识别结果，-1表示负面，1表示正面，0不确定
     * </pre>
     */
    int getSentiment();

    // required double posRate = 3;
    /**
     * <code>required double posRate = 3;</code>
     *
     * <pre>
     *新闻是正面的概率
     * </pre>
     */
    boolean hasPosRate();
    /**
     * <code>required double posRate = 3;</code>
     *
     * <pre>
     *新闻是正面的概率
     * </pre>
     */
    double getPosRate();

    // required double negRate = 4;
    /**
     * <code>required double negRate = 4;</code>
     *
     * <pre>
     *新闻是负面的概率
     * </pre>
     */
    boolean hasNegRate();
    /**
     * <code>required double negRate = 4;</code>
     *
     * <pre>
     *新闻是负面的概率
     * </pre>
     */
    double getNegRate();

    // required int64 processTime = 5;
    /**
     * <code>required int64 processTime = 5;</code>
     *
     * <pre>
     *处理这篇新闻所用的时间
     * </pre>
     */
    boolean hasProcessTime();
    /**
     * <code>required int64 processTime = 5;</code>
     *
     * <pre>
     *处理这篇新闻所用的时间
     * </pre>
     */
    long getProcessTime();

    // required string title = 6;
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string text = 7;
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    // required string result = 8;
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    java.lang.String getResult();
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    // repeated string classNameList = 9;
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    java.util.List<java.lang.String>
    getClassNameListList();
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    int getClassNameListCount();
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    java.lang.String getClassNameList(int index);
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getClassNameListBytes(int index);

    // repeated string companyNames = 10;
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    java.util.List<java.lang.String>
    getCompanyNamesList();
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    int getCompanyNamesCount();
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    java.lang.String getCompanyNames(int index);
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    com.google.protobuf.ByteString
        getCompanyNamesBytes(int index);
  }
  /**
   * Protobuf type {@code NewsSentiment}
   */
  public static final class NewsSentiment extends
      com.google.protobuf.GeneratedMessageLite
      implements NewsSentimentOrBuilder {
    // Use NewsSentiment.newBuilder() to construct.
    private NewsSentiment(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private NewsSentiment(boolean noInit) {}

    private static final NewsSentiment defaultInstance;
    public static NewsSentiment getDefaultInstance() {
      return defaultInstance;
    }

    public NewsSentiment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private NewsSentiment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sentiment_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              posRate_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              negRate_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              processTime_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              title_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              text_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              result_ = input.readBytes();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                classNameList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000100;
              }
              classNameList_.add(input.readBytes());
              break;
            }
            case 82: {
              if (!((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
                companyNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000200;
              }
              companyNames_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(classNameList_);
        }
        if (((mutable_bitField0_ & 0x00000200) == 0x00000200)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(companyNames_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<NewsSentiment> PARSER =
        new com.google.protobuf.AbstractParser<NewsSentiment>() {
      public NewsSentiment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsSentiment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewsSentiment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private long newsCode_;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public long getNewsCode() {
      return newsCode_;
    }

    // required int32 sentiment = 2;
    public static final int SENTIMENT_FIELD_NUMBER = 2;
    private int sentiment_;
    /**
     * <code>required int32 sentiment = 2;</code>
     *
     * <pre>
     *新闻情感识别结果，-1表示负面，1表示正面，0不确定
     * </pre>
     */
    public boolean hasSentiment() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 sentiment = 2;</code>
     *
     * <pre>
     *新闻情感识别结果，-1表示负面，1表示正面，0不确定
     * </pre>
     */
    public int getSentiment() {
      return sentiment_;
    }

    // required double posRate = 3;
    public static final int POSRATE_FIELD_NUMBER = 3;
    private double posRate_;
    /**
     * <code>required double posRate = 3;</code>
     *
     * <pre>
     *新闻是正面的概率
     * </pre>
     */
    public boolean hasPosRate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double posRate = 3;</code>
     *
     * <pre>
     *新闻是正面的概率
     * </pre>
     */
    public double getPosRate() {
      return posRate_;
    }

    // required double negRate = 4;
    public static final int NEGRATE_FIELD_NUMBER = 4;
    private double negRate_;
    /**
     * <code>required double negRate = 4;</code>
     *
     * <pre>
     *新闻是负面的概率
     * </pre>
     */
    public boolean hasNegRate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double negRate = 4;</code>
     *
     * <pre>
     *新闻是负面的概率
     * </pre>
     */
    public double getNegRate() {
      return negRate_;
    }

    // required int64 processTime = 5;
    public static final int PROCESSTIME_FIELD_NUMBER = 5;
    private long processTime_;
    /**
     * <code>required int64 processTime = 5;</code>
     *
     * <pre>
     *处理这篇新闻所用的时间
     * </pre>
     */
    public boolean hasProcessTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 processTime = 5;</code>
     *
     * <pre>
     *处理这篇新闻所用的时间
     * </pre>
     */
    public long getProcessTime() {
      return processTime_;
    }

    // required string title = 6;
    public static final int TITLE_FIELD_NUMBER = 6;
    private java.lang.Object title_;
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 6;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string text = 7;
    public static final int TEXT_FIELD_NUMBER = 7;
    private java.lang.Object text_;
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string text = 7;</code>
     *
     * <pre>
     *去除垃圾后的新闻内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string result = 8;
    public static final int RESULT_FIELD_NUMBER = 8;
    private java.lang.Object result_;
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result = 8;</code>
     *
     * <pre>
     *具体分类分数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string classNameList = 9;
    public static final int CLASSNAMELIST_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList classNameList_;
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    public java.util.List<java.lang.String>
        getClassNameListList() {
      return classNameList_;
    }
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    public int getClassNameListCount() {
      return classNameList_.size();
    }
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    public java.lang.String getClassNameList(int index) {
      return classNameList_.get(index);
    }
    /**
     * <code>repeated string classNameList = 9;</code>
     *
     * <pre>
     *公司分类名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClassNameListBytes(int index) {
      return classNameList_.getByteString(index);
    }

    // repeated string companyNames = 10;
    public static final int COMPANYNAMES_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList companyNames_;
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    public java.util.List<java.lang.String>
        getCompanyNamesList() {
      return companyNames_;
    }
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    public java.lang.String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    /**
     * <code>repeated string companyNames = 10;</code>
     *
     * <pre>
     *公司
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCompanyNamesBytes(int index) {
      return companyNames_.getByteString(index);
    }

    private void initFields() {
      newsCode_ = 0L;
      sentiment_ = 0;
      posRate_ = 0D;
      negRate_ = 0D;
      processTime_ = 0L;
      title_ = "";
      text_ = "";
      result_ = "";
      classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSentiment()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosRate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNegRate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProcessTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sentiment_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, posRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, negRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, processTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getResultBytes());
      }
      for (int i = 0; i < classNameList_.size(); i++) {
        output.writeBytes(9, classNameList_.getByteString(i));
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(10, companyNames_.getByteString(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sentiment_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, posRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, negRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, processTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getResultBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(classNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code NewsSentiment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment, Builder>
        implements com.gw.ps.pbbean.PbNewsSentiment.NewsSentimentOrBuilder {
      // Construct using com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newsCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sentiment_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        posRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        negRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        processTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment getDefaultInstanceForType() {
        return com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment.getDefaultInstance();
      }

      public com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment build() {
        com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment buildPartial() {
        com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment result = new com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sentiment_ = sentiment_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posRate_ = posRate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.negRate_ = negRate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.processTime_ = processTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.result_ = result_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              classNameList_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.classNameList_ = classNameList_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.companyNames_ = companyNames_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment other) {
        if (other == com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasSentiment()) {
          setSentiment(other.getSentiment());
        }
        if (other.hasPosRate()) {
          setPosRate(other.getPosRate());
        }
        if (other.hasNegRate()) {
          setNegRate(other.getNegRate());
        }
        if (other.hasProcessTime()) {
          setProcessTime(other.getProcessTime());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000020;
          title_ = other.title_;
          
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000040;
          text_ = other.text_;
          
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000080;
          result_ = other.result_;
          
        }
        if (!other.classNameList_.isEmpty()) {
          if (classNameList_.isEmpty()) {
            classNameList_ = other.classNameList_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureClassNameListIsMutable();
            classNameList_.addAll(other.classNameList_);
          }
          
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasSentiment()) {
          
          return false;
        }
        if (!hasPosRate()) {
          
          return false;
        }
        if (!hasNegRate()) {
          
          return false;
        }
        if (!hasProcessTime()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ps.pbbean.PbNewsSentiment.NewsSentiment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 newsCode = 1;
      private long newsCode_ ;
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public long getNewsCode() {
        return newsCode_;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder setNewsCode(long value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        
        return this;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = 0L;
        
        return this;
      }

      // required int32 sentiment = 2;
      private int sentiment_ ;
      /**
       * <code>required int32 sentiment = 2;</code>
       *
       * <pre>
       *新闻情感识别结果，-1表示负面，1表示正面，0不确定
       * </pre>
       */
      public boolean hasSentiment() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 sentiment = 2;</code>
       *
       * <pre>
       *新闻情感识别结果，-1表示负面，1表示正面，0不确定
       * </pre>
       */
      public int getSentiment() {
        return sentiment_;
      }
      /**
       * <code>required int32 sentiment = 2;</code>
       *
       * <pre>
       *新闻情感识别结果，-1表示负面，1表示正面，0不确定
       * </pre>
       */
      public Builder setSentiment(int value) {
        bitField0_ |= 0x00000002;
        sentiment_ = value;
        
        return this;
      }
      /**
       * <code>required int32 sentiment = 2;</code>
       *
       * <pre>
       *新闻情感识别结果，-1表示负面，1表示正面，0不确定
       * </pre>
       */
      public Builder clearSentiment() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sentiment_ = 0;
        
        return this;
      }

      // required double posRate = 3;
      private double posRate_ ;
      /**
       * <code>required double posRate = 3;</code>
       *
       * <pre>
       *新闻是正面的概率
       * </pre>
       */
      public boolean hasPosRate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double posRate = 3;</code>
       *
       * <pre>
       *新闻是正面的概率
       * </pre>
       */
      public double getPosRate() {
        return posRate_;
      }
      /**
       * <code>required double posRate = 3;</code>
       *
       * <pre>
       *新闻是正面的概率
       * </pre>
       */
      public Builder setPosRate(double value) {
        bitField0_ |= 0x00000004;
        posRate_ = value;
        
        return this;
      }
      /**
       * <code>required double posRate = 3;</code>
       *
       * <pre>
       *新闻是正面的概率
       * </pre>
       */
      public Builder clearPosRate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posRate_ = 0D;
        
        return this;
      }

      // required double negRate = 4;
      private double negRate_ ;
      /**
       * <code>required double negRate = 4;</code>
       *
       * <pre>
       *新闻是负面的概率
       * </pre>
       */
      public boolean hasNegRate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double negRate = 4;</code>
       *
       * <pre>
       *新闻是负面的概率
       * </pre>
       */
      public double getNegRate() {
        return negRate_;
      }
      /**
       * <code>required double negRate = 4;</code>
       *
       * <pre>
       *新闻是负面的概率
       * </pre>
       */
      public Builder setNegRate(double value) {
        bitField0_ |= 0x00000008;
        negRate_ = value;
        
        return this;
      }
      /**
       * <code>required double negRate = 4;</code>
       *
       * <pre>
       *新闻是负面的概率
       * </pre>
       */
      public Builder clearNegRate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        negRate_ = 0D;
        
        return this;
      }

      // required int64 processTime = 5;
      private long processTime_ ;
      /**
       * <code>required int64 processTime = 5;</code>
       *
       * <pre>
       *处理这篇新闻所用的时间
       * </pre>
       */
      public boolean hasProcessTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 processTime = 5;</code>
       *
       * <pre>
       *处理这篇新闻所用的时间
       * </pre>
       */
      public long getProcessTime() {
        return processTime_;
      }
      /**
       * <code>required int64 processTime = 5;</code>
       *
       * <pre>
       *处理这篇新闻所用的时间
       * </pre>
       */
      public Builder setProcessTime(long value) {
        bitField0_ |= 0x00000010;
        processTime_ = value;
        
        return this;
      }
      /**
       * <code>required int64 processTime = 5;</code>
       *
       * <pre>
       *处理这篇新闻所用的时间
       * </pre>
       */
      public Builder clearProcessTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        processTime_ = 0L;
        
        return this;
      }

      // required string title = 6;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        
        return this;
      }
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      /**
       * <code>required string title = 6;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        
        return this;
      }

      // required string text = 7;
      private java.lang.Object text_ = "";
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        text_ = value;
        
        return this;
      }
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      /**
       * <code>required string text = 7;</code>
       *
       * <pre>
       *去除垃圾后的新闻内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        text_ = value;
        
        return this;
      }

      // required string result = 8;
      private java.lang.Object result_ = "";
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        result_ = value;
        
        return this;
      }
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000080);
        result_ = getDefaultInstance().getResult();
        
        return this;
      }
      /**
       * <code>required string result = 8;</code>
       *
       * <pre>
       *具体分类分数
       * </pre>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        result_ = value;
        
        return this;
      }

      // repeated string classNameList = 9;
      private com.google.protobuf.LazyStringList classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameListIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          classNameList_ = new com.google.protobuf.LazyStringArrayList(classNameList_);
          bitField0_ |= 0x00000100;
         }
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public java.util.List<java.lang.String>
          getClassNameListList() {
        return java.util.Collections.unmodifiableList(classNameList_);
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public int getClassNameListCount() {
        return classNameList_.size();
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public java.lang.String getClassNameList(int index) {
        return classNameList_.get(index);
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClassNameListBytes(int index) {
        return classNameList_.getByteString(index);
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public Builder setClassNameList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public Builder addClassNameList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public Builder addAllClassNameList(
          java.lang.Iterable<java.lang.String> values) {
        ensureClassNameListIsMutable();
        super.addAll(values, classNameList_);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public Builder clearClassNameList() {
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 9;</code>
       *
       * <pre>
       *公司分类名称
       * </pre>
       */
      public Builder addClassNameListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }

      // repeated string companyNames = 10;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000200;
         }
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public java.util.List<java.lang.String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public java.lang.String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCompanyNamesBytes(int index) {
        return companyNames_.getByteString(index);
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public Builder setCompanyNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public Builder addCompanyNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public Builder addAllCompanyNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 10;</code>
       *
       * <pre>
       *公司
       * </pre>
       */
      public Builder addCompanyNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewsSentiment)
    }

    static {
      defaultInstance = new NewsSentiment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewsSentiment)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
