// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsSentiInner.proto

package com.gw.ps.pbbean;

public final class PbNewsInnerUsing {
  private PbNewsInnerUsing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface InnerNewsOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required int64 newsCode = 1;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    boolean hasNewsCode();
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    long getNewsCode();

    // required string result = 2;
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    java.lang.String getResult();
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    // repeated string classNameList = 3;
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    java.util.List<java.lang.String>
    getClassNameListList();
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    int getClassNameListCount();
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    java.lang.String getClassNameList(int index);
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    com.google.protobuf.ByteString
        getClassNameListBytes(int index);

    // required string title = 4;
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string content = 5;
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    // repeated string companyNames = 6;
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    java.util.List<java.lang.String>
    getCompanyNamesList();
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    int getCompanyNamesCount();
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    java.lang.String getCompanyNames(int index);
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    com.google.protobuf.ByteString
        getCompanyNamesBytes(int index);

    // required bool isFiltered = 7;
    /**
     * <code>required bool isFiltered = 7;</code>
     *
     * <pre>
     *是否被过滤
     * </pre>
     */
    boolean hasIsFiltered();
    /**
     * <code>required bool isFiltered = 7;</code>
     *
     * <pre>
     *是否被过滤
     * </pre>
     */
    boolean getIsFiltered();

    // required string source = 8;
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    boolean hasSource();
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    java.lang.String getSource();
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    com.google.protobuf.ByteString
        getSourceBytes();
  }
  /**
   * Protobuf type {@code InnerNews}
   */
  public static final class InnerNews extends
      com.google.protobuf.GeneratedMessageLite
      implements InnerNewsOrBuilder {
    // Use InnerNews.newBuilder() to construct.
    private InnerNews(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private InnerNews(boolean noInit) {}

    private static final InnerNews defaultInstance;
    public static InnerNews getDefaultInstance() {
      return defaultInstance;
    }

    public InnerNews getDefaultInstanceForType() {
      return defaultInstance;
    }

    private InnerNews(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              result_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                classNameList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              classNameList_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              title_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                companyNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              companyNames_.add(input.readBytes());
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              isFiltered_ = input.readBool();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000020;
              source_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(classNameList_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(companyNames_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<InnerNews> PARSER =
        new com.google.protobuf.AbstractParser<InnerNews>() {
      public InnerNews parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InnerNews(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<InnerNews> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private long newsCode_;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public long getNewsCode() {
      return newsCode_;
    }

    // required string result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private java.lang.Object result_;
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *行业结果
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string classNameList = 3;
    public static final int CLASSNAMELIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList classNameList_;
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    public java.util.List<java.lang.String>
        getClassNameListList() {
      return classNameList_;
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    public int getClassNameListCount() {
      return classNameList_.size();
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    public java.lang.String getClassNameList(int index) {
      return classNameList_.get(index);
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *行业（可有多个）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClassNameListBytes(int index) {
      return classNameList_.getByteString(index);
    }

    // required string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *新闻标题
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.Object content_;
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string companyNames = 6;
    public static final int COMPANYNAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList companyNames_;
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    public java.util.List<java.lang.String>
        getCompanyNamesList() {
      return companyNames_;
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    public java.lang.String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名（可有多个）
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCompanyNamesBytes(int index) {
      return companyNames_.getByteString(index);
    }

    // required bool isFiltered = 7;
    public static final int ISFILTERED_FIELD_NUMBER = 7;
    private boolean isFiltered_;
    /**
     * <code>required bool isFiltered = 7;</code>
     *
     * <pre>
     *是否被过滤
     * </pre>
     */
    public boolean hasIsFiltered() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool isFiltered = 7;</code>
     *
     * <pre>
     *是否被过滤
     * </pre>
     */
    public boolean getIsFiltered() {
      return isFiltered_;
    }

    // required string source = 8;
    public static final int SOURCE_FIELD_NUMBER = 8;
    private java.lang.Object source_;
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    public java.lang.String getSource() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          source_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string source = 8;</code>
     *
     * <pre>
     *新闻来源
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      java.lang.Object ref = source_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      newsCode_ = 0L;
      result_ = "";
      classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      title_ = "";
      content_ = "";
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      isFiltered_ = false;
      source_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsFiltered()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultBytes());
      }
      for (int i = 0; i < classNameList_.size(); i++) {
        output.writeBytes(3, classNameList_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getContentBytes());
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(6, companyNames_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(7, isFiltered_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(8, getSourceBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(classNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameListList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isFiltered_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSourceBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code InnerNews}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews, Builder>
        implements com.gw.ps.pbbean.PbNewsInnerUsing.InnerNewsOrBuilder {
      // Construct using com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newsCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        isFiltered_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        source_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews getDefaultInstanceForType() {
        return com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews.getDefaultInstance();
      }

      public com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews build() {
        com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews buildPartial() {
        com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews result = new com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              classNameList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.classNameList_ = classNameList_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.companyNames_ = companyNames_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.isFiltered_ = isFiltered_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000020;
        }
        result.source_ = source_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews other) {
        if (other == com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000002;
          result_ = other.result_;
          
        }
        if (!other.classNameList_.isEmpty()) {
          if (classNameList_.isEmpty()) {
            classNameList_ = other.classNameList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClassNameListIsMutable();
            classNameList_.addAll(other.classNameList_);
          }
          
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000008;
          title_ = other.title_;
          
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          
        }
        if (other.hasIsFiltered()) {
          setIsFiltered(other.getIsFiltered());
        }
        if (other.hasSource()) {
          bitField0_ |= 0x00000080;
          source_ = other.source_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (!hasIsFiltered()) {
          
          return false;
        }
        if (!hasSource()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ps.pbbean.PbNewsInnerUsing.InnerNews) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 newsCode = 1;
      private long newsCode_ ;
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public long getNewsCode() {
        return newsCode_;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder setNewsCode(long value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        
        return this;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = 0L;
        
        return this;
      }

      // required string result = 2;
      private java.lang.Object result_ = "";
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        result_ = value;
        
        return this;
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = getDefaultInstance().getResult();
        
        return this;
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *行业结果
       * </pre>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        result_ = value;
        
        return this;
      }

      // repeated string classNameList = 3;
      private com.google.protobuf.LazyStringList classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.LazyStringArrayList(classNameList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public java.util.List<java.lang.String>
          getClassNameListList() {
        return java.util.Collections.unmodifiableList(classNameList_);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public int getClassNameListCount() {
        return classNameList_.size();
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public java.lang.String getClassNameList(int index) {
        return classNameList_.get(index);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClassNameListBytes(int index) {
        return classNameList_.getByteString(index);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public Builder setClassNameList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public Builder addClassNameList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public Builder addAllClassNameList(
          java.lang.Iterable<java.lang.String> values) {
        ensureClassNameListIsMutable();
        super.addAll(values, classNameList_);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public Builder clearClassNameList() {
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *行业（可有多个）
       * </pre>
       */
      public Builder addClassNameListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }

      // required string title = 4;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *新闻标题
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        
        return this;
      }

      // required string content = 5;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        
        return this;
      }

      // repeated string companyNames = 6;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public java.util.List<java.lang.String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public java.lang.String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCompanyNamesBytes(int index) {
        return companyNames_.getByteString(index);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public Builder setCompanyNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public Builder addCompanyNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public Builder addAllCompanyNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名（可有多个）
       * </pre>
       */
      public Builder addCompanyNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }

      // required bool isFiltered = 7;
      private boolean isFiltered_ ;
      /**
       * <code>required bool isFiltered = 7;</code>
       *
       * <pre>
       *是否被过滤
       * </pre>
       */
      public boolean hasIsFiltered() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required bool isFiltered = 7;</code>
       *
       * <pre>
       *是否被过滤
       * </pre>
       */
      public boolean getIsFiltered() {
        return isFiltered_;
      }
      /**
       * <code>required bool isFiltered = 7;</code>
       *
       * <pre>
       *是否被过滤
       * </pre>
       */
      public Builder setIsFiltered(boolean value) {
        bitField0_ |= 0x00000040;
        isFiltered_ = value;
        
        return this;
      }
      /**
       * <code>required bool isFiltered = 7;</code>
       *
       * <pre>
       *是否被过滤
       * </pre>
       */
      public Builder clearIsFiltered() {
        bitField0_ = (bitField0_ & ~0x00000040);
        isFiltered_ = false;
        
        return this;
      }

      // required string source = 8;
      private java.lang.Object source_ = "";
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public java.lang.String getSource() {
        java.lang.Object ref = source_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        java.lang.Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public Builder setSource(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        source_ = value;
        
        return this;
      }
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000080);
        source_ = getDefaultInstance().getSource();
        
        return this;
      }
      /**
       * <code>required string source = 8;</code>
       *
       * <pre>
       *新闻来源
       * </pre>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        source_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:InnerNews)
    }

    static {
      defaultInstance = new InnerNews(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:InnerNews)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
