// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsSentimentUntreated.proto

package com.gw.ps.pbbean;

public final class PbNewsSentimentUntreated {
  private PbNewsSentimentUntreated() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NewsSentimentUntreatedOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string newsCode = 1;
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    boolean hasNewsCode();
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    java.lang.String getNewsCode();
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getNewsCodeBytes();

    // optional string title = 2;
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // optional string text = 3;
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    boolean hasText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    // optional string newsType = 4;
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    boolean hasNewsType();
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    java.lang.String getNewsType();
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    com.google.protobuf.ByteString
        getNewsTypeBytes();

    // repeated string companyIds = 5;
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    java.util.List<java.lang.String>
    getCompanyIdsList();
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    int getCompanyIdsCount();
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    java.lang.String getCompanyIds(int index);
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    com.google.protobuf.ByteString
        getCompanyIdsBytes(int index);

    // repeated string companyNames = 6;
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    java.util.List<java.lang.String>
    getCompanyNamesList();
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    int getCompanyNamesCount();
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    java.lang.String getCompanyNames(int index);
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getCompanyNamesBytes(int index);

    // repeated string industryIds = 7;
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    java.util.List<java.lang.String>
    getIndustryIdsList();
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    int getIndustryIdsCount();
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    java.lang.String getIndustryIds(int index);
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    com.google.protobuf.ByteString
        getIndustryIdsBytes(int index);

    // repeated string industryNames = 8;
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    java.util.List<java.lang.String>
    getIndustryNamesList();
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    int getIndustryNamesCount();
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    java.lang.String getIndustryNames(int index);
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getIndustryNamesBytes(int index);

    // optional string entryDate = 9;
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    boolean hasEntryDate();
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    java.lang.String getEntryDate();
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getEntryDateBytes();

    // optional string typeOf = 10;
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    boolean hasTypeOf();
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    java.lang.String getTypeOf();
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeOfBytes();

    // optional string publishdate = 11;
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    boolean hasPublishdate();
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    java.lang.String getPublishdate();
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getPublishdateBytes();
  }
  /**
   * Protobuf type {@code NewsSentimentUntreated}
   */
  public static final class NewsSentimentUntreated extends
      com.google.protobuf.GeneratedMessageLite
      implements NewsSentimentUntreatedOrBuilder {
    // Use NewsSentimentUntreated.newBuilder() to construct.
    private NewsSentimentUntreated(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private NewsSentimentUntreated(boolean noInit) {}

    private static final NewsSentimentUntreated defaultInstance;
    public static NewsSentimentUntreated getDefaultInstance() {
      return defaultInstance;
    }

    public NewsSentimentUntreated getDefaultInstanceForType() {
      return defaultInstance;
    }

    private NewsSentimentUntreated(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              newsType_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                companyIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              companyIds_.add(input.readBytes());
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                companyNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000020;
              }
              companyNames_.add(input.readBytes());
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                industryIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              industryIds_.add(input.readBytes());
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                industryNames_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              industryNames_.add(input.readBytes());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000010;
              entryDate_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000020;
              typeOf_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000040;
              publishdate_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          companyIds_ = new com.google.protobuf.UnmodifiableLazyStringList(companyIds_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(companyNames_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          industryIds_ = new com.google.protobuf.UnmodifiableLazyStringList(industryIds_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          industryNames_ = new com.google.protobuf.UnmodifiableLazyStringList(industryNames_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<NewsSentimentUntreated> PARSER =
        new com.google.protobuf.AbstractParser<NewsSentimentUntreated>() {
      public NewsSentimentUntreated parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsSentimentUntreated(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewsSentimentUntreated> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private java.lang.Object newsCode_;
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public java.lang.String getNewsCode() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newsCode_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string newsCode = 1;</code>
     *
     * <pre>
     *新闻ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNewsCodeBytes() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newsCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 3;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string newsType = 4;
    public static final int NEWSTYPE_FIELD_NUMBER = 4;
    private java.lang.Object newsType_;
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    public boolean hasNewsType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    public java.lang.String getNewsType() {
      java.lang.Object ref = newsType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          newsType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string newsType = 4;</code>
     *
     * <pre>
     *新闻类型
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNewsTypeBytes() {
      java.lang.Object ref = newsType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        newsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string companyIds = 5;
    public static final int COMPANYIDS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList companyIds_;
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    public java.util.List<java.lang.String>
        getCompanyIdsList() {
      return companyIds_;
    }
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    public int getCompanyIdsCount() {
      return companyIds_.size();
    }
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    public java.lang.String getCompanyIds(int index) {
      return companyIds_.get(index);
    }
    /**
     * <code>repeated string companyIds = 5;</code>
     *
     * <pre>
     *公司Id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCompanyIdsBytes(int index) {
      return companyIds_.getByteString(index);
    }

    // repeated string companyNames = 6;
    public static final int COMPANYNAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList companyNames_;
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    public java.util.List<java.lang.String>
        getCompanyNamesList() {
      return companyNames_;
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    public java.lang.String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    /**
     * <code>repeated string companyNames = 6;</code>
     *
     * <pre>
     *公司名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCompanyNamesBytes(int index) {
      return companyNames_.getByteString(index);
    }

    // repeated string industryIds = 7;
    public static final int INDUSTRYIDS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList industryIds_;
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    public java.util.List<java.lang.String>
        getIndustryIdsList() {
      return industryIds_;
    }
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    public int getIndustryIdsCount() {
      return industryIds_.size();
    }
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    public java.lang.String getIndustryIds(int index) {
      return industryIds_.get(index);
    }
    /**
     * <code>repeated string industryIds = 7;</code>
     *
     * <pre>
     *行业Id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIndustryIdsBytes(int index) {
      return industryIds_.getByteString(index);
    }

    // repeated string industryNames = 8;
    public static final int INDUSTRYNAMES_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList industryNames_;
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    public java.util.List<java.lang.String>
        getIndustryNamesList() {
      return industryNames_;
    }
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    public int getIndustryNamesCount() {
      return industryNames_.size();
    }
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    public java.lang.String getIndustryNames(int index) {
      return industryNames_.get(index);
    }
    /**
     * <code>repeated string industryNames = 8;</code>
     *
     * <pre>
     *行业名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIndustryNamesBytes(int index) {
      return industryNames_.getByteString(index);
    }

    // optional string entryDate = 9;
    public static final int ENTRYDATE_FIELD_NUMBER = 9;
    private java.lang.Object entryDate_;
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    public boolean hasEntryDate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    public java.lang.String getEntryDate() {
      java.lang.Object ref = entryDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          entryDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string entryDate = 9;</code>
     *
     * <pre>
     *流入时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getEntryDateBytes() {
      java.lang.Object ref = entryDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        entryDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string typeOf = 10;
    public static final int TYPEOF_FIELD_NUMBER = 10;
    private java.lang.Object typeOf_;
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    public boolean hasTypeOf() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    public java.lang.String getTypeOf() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          typeOf_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string typeOf = 10;</code>
     *
     * <pre>
     *类型 新闻/微博/其他
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeOfBytes() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeOf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string publishdate = 11;
    public static final int PUBLISHDATE_FIELD_NUMBER = 11;
    private java.lang.Object publishdate_;
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    public boolean hasPublishdate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    public java.lang.String getPublishdate() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          publishdate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string publishdate = 11;</code>
     *
     * <pre>
     *新闻发布时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPublishdateBytes() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publishdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      newsCode_ = "";
      title_ = "";
      text_ = "";
      newsType_ = "";
      companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      entryDate_ = "";
      typeOf_ = "";
      publishdate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNewsTypeBytes());
      }
      for (int i = 0; i < companyIds_.size(); i++) {
        output.writeBytes(5, companyIds_.getByteString(i));
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(6, companyNames_.getByteString(i));
      }
      for (int i = 0; i < industryIds_.size(); i++) {
        output.writeBytes(7, industryIds_.getByteString(i));
      }
      for (int i = 0; i < industryNames_.size(); i++) {
        output.writeBytes(8, industryNames_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(9, getEntryDateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(10, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(11, getPublishdateBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNewsTypeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyIds_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < industryIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(industryIds_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIndustryIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < industryNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(industryNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIndustryNamesList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getEntryDateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPublishdateBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code NewsSentimentUntreated}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated, Builder>
        implements com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreatedOrBuilder {
      // Construct using com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newsCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        newsType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        entryDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        typeOf_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        publishdate_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated getDefaultInstanceForType() {
        return com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated.getDefaultInstance();
      }

      public com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated build() {
        com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated buildPartial() {
        com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated result = new com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newsType_ = newsType_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          companyIds_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyIds_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.companyIds_ = companyIds_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.companyNames_ = companyNames_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          industryIds_ = new com.google.protobuf.UnmodifiableLazyStringList(
              industryIds_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.industryIds_ = industryIds_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          industryNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              industryNames_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.industryNames_ = industryNames_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000010;
        }
        result.entryDate_ = entryDate_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000020;
        }
        result.typeOf_ = typeOf_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000040;
        }
        result.publishdate_ = publishdate_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated other) {
        if (other == com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          bitField0_ |= 0x00000001;
          newsCode_ = other.newsCode_;
          
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          
        }
        if (other.hasText()) {
          bitField0_ |= 0x00000004;
          text_ = other.text_;
          
        }
        if (other.hasNewsType()) {
          bitField0_ |= 0x00000008;
          newsType_ = other.newsType_;
          
        }
        if (!other.companyIds_.isEmpty()) {
          if (companyIds_.isEmpty()) {
            companyIds_ = other.companyIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCompanyIdsIsMutable();
            companyIds_.addAll(other.companyIds_);
          }
          
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          
        }
        if (!other.industryIds_.isEmpty()) {
          if (industryIds_.isEmpty()) {
            industryIds_ = other.industryIds_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureIndustryIdsIsMutable();
            industryIds_.addAll(other.industryIds_);
          }
          
        }
        if (!other.industryNames_.isEmpty()) {
          if (industryNames_.isEmpty()) {
            industryNames_ = other.industryNames_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureIndustryNamesIsMutable();
            industryNames_.addAll(other.industryNames_);
          }
          
        }
        if (other.hasEntryDate()) {
          bitField0_ |= 0x00000100;
          entryDate_ = other.entryDate_;
          
        }
        if (other.hasTypeOf()) {
          bitField0_ |= 0x00000200;
          typeOf_ = other.typeOf_;
          
        }
        if (other.hasPublishdate()) {
          bitField0_ |= 0x00000400;
          publishdate_ = other.publishdate_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ps.pbbean.PbNewsSentimentUntreated.NewsSentimentUntreated) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string newsCode = 1;
      private java.lang.Object newsCode_ = "";
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public java.lang.String getNewsCode() {
        java.lang.Object ref = newsCode_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newsCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNewsCodeBytes() {
        java.lang.Object ref = newsCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newsCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder setNewsCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newsCode_ = value;
        
        return this;
      }
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = getDefaultInstance().getNewsCode();
        
        return this;
      }
      /**
       * <code>required string newsCode = 1;</code>
       *
       * <pre>
       *新闻ID
       * </pre>
       */
      public Builder setNewsCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newsCode_ = value;
        
        return this;
      }

      // optional string title = 2;
      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        
        return this;
      }

      // optional string text = 3;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        
        return this;
      }
      /**
       * <code>optional string text = 3;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        
        return this;
      }

      // optional string newsType = 4;
      private java.lang.Object newsType_ = "";
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public boolean hasNewsType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public java.lang.String getNewsType() {
        java.lang.Object ref = newsType_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          newsType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNewsTypeBytes() {
        java.lang.Object ref = newsType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          newsType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public Builder setNewsType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        newsType_ = value;
        
        return this;
      }
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public Builder clearNewsType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newsType_ = getDefaultInstance().getNewsType();
        
        return this;
      }
      /**
       * <code>optional string newsType = 4;</code>
       *
       * <pre>
       *新闻类型
       * </pre>
       */
      public Builder setNewsTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        newsType_ = value;
        
        return this;
      }

      // repeated string companyIds = 5;
      private com.google.protobuf.LazyStringList companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          companyIds_ = new com.google.protobuf.LazyStringArrayList(companyIds_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public java.util.List<java.lang.String>
          getCompanyIdsList() {
        return java.util.Collections.unmodifiableList(companyIds_);
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public int getCompanyIdsCount() {
        return companyIds_.size();
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public java.lang.String getCompanyIds(int index) {
        return companyIds_.get(index);
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCompanyIdsBytes(int index) {
        return companyIds_.getByteString(index);
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public Builder setCompanyIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyIdsIsMutable();
        companyIds_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public Builder addCompanyIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyIdsIsMutable();
        companyIds_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public Builder addAllCompanyIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureCompanyIdsIsMutable();
        super.addAll(values, companyIds_);
        
        return this;
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public Builder clearCompanyIds() {
        companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }
      /**
       * <code>repeated string companyIds = 5;</code>
       *
       * <pre>
       *公司Id
       * </pre>
       */
      public Builder addCompanyIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyIdsIsMutable();
        companyIds_.add(value);
        
        return this;
      }

      // repeated string companyNames = 6;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000020;
         }
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public java.util.List<java.lang.String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public java.lang.String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCompanyNamesBytes(int index) {
        return companyNames_.getByteString(index);
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public Builder setCompanyNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public Builder addCompanyNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public Builder addAllCompanyNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        
        return this;
      }
      /**
       * <code>repeated string companyNames = 6;</code>
       *
       * <pre>
       *公司名称
       * </pre>
       */
      public Builder addCompanyNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        
        return this;
      }

      // repeated string industryIds = 7;
      private com.google.protobuf.LazyStringList industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndustryIdsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          industryIds_ = new com.google.protobuf.LazyStringArrayList(industryIds_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public java.util.List<java.lang.String>
          getIndustryIdsList() {
        return java.util.Collections.unmodifiableList(industryIds_);
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public int getIndustryIdsCount() {
        return industryIds_.size();
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public java.lang.String getIndustryIds(int index) {
        return industryIds_.get(index);
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIndustryIdsBytes(int index) {
        return industryIds_.getByteString(index);
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public Builder setIndustryIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryIdsIsMutable();
        industryIds_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public Builder addIndustryIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryIdsIsMutable();
        industryIds_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public Builder addAllIndustryIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureIndustryIdsIsMutable();
        super.addAll(values, industryIds_);
        
        return this;
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public Builder clearIndustryIds() {
        industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        
        return this;
      }
      /**
       * <code>repeated string industryIds = 7;</code>
       *
       * <pre>
       *行业Id
       * </pre>
       */
      public Builder addIndustryIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryIdsIsMutable();
        industryIds_.add(value);
        
        return this;
      }

      // repeated string industryNames = 8;
      private com.google.protobuf.LazyStringList industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndustryNamesIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          industryNames_ = new com.google.protobuf.LazyStringArrayList(industryNames_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public java.util.List<java.lang.String>
          getIndustryNamesList() {
        return java.util.Collections.unmodifiableList(industryNames_);
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public int getIndustryNamesCount() {
        return industryNames_.size();
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public java.lang.String getIndustryNames(int index) {
        return industryNames_.get(index);
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIndustryNamesBytes(int index) {
        return industryNames_.getByteString(index);
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public Builder setIndustryNames(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryNamesIsMutable();
        industryNames_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public Builder addIndustryNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryNamesIsMutable();
        industryNames_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public Builder addAllIndustryNames(
          java.lang.Iterable<java.lang.String> values) {
        ensureIndustryNamesIsMutable();
        super.addAll(values, industryNames_);
        
        return this;
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public Builder clearIndustryNames() {
        industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        
        return this;
      }
      /**
       * <code>repeated string industryNames = 8;</code>
       *
       * <pre>
       *行业名称
       * </pre>
       */
      public Builder addIndustryNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryNamesIsMutable();
        industryNames_.add(value);
        
        return this;
      }

      // optional string entryDate = 9;
      private java.lang.Object entryDate_ = "";
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public boolean hasEntryDate() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public java.lang.String getEntryDate() {
        java.lang.Object ref = entryDate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          entryDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getEntryDateBytes() {
        java.lang.Object ref = entryDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          entryDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public Builder setEntryDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        entryDate_ = value;
        
        return this;
      }
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public Builder clearEntryDate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        entryDate_ = getDefaultInstance().getEntryDate();
        
        return this;
      }
      /**
       * <code>optional string entryDate = 9;</code>
       *
       * <pre>
       *流入时间
       * </pre>
       */
      public Builder setEntryDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        entryDate_ = value;
        
        return this;
      }

      // optional string typeOf = 10;
      private java.lang.Object typeOf_ = "";
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public boolean hasTypeOf() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public java.lang.String getTypeOf() {
        java.lang.Object ref = typeOf_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          typeOf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeOfBytes() {
        java.lang.Object ref = typeOf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          typeOf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public Builder setTypeOf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        typeOf_ = value;
        
        return this;
      }
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public Builder clearTypeOf() {
        bitField0_ = (bitField0_ & ~0x00000200);
        typeOf_ = getDefaultInstance().getTypeOf();
        
        return this;
      }
      /**
       * <code>optional string typeOf = 10;</code>
       *
       * <pre>
       *类型 新闻/微博/其他
       * </pre>
       */
      public Builder setTypeOfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        typeOf_ = value;
        
        return this;
      }

      // optional string publishdate = 11;
      private java.lang.Object publishdate_ = "";
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public boolean hasPublishdate() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public java.lang.String getPublishdate() {
        java.lang.Object ref = publishdate_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          publishdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPublishdateBytes() {
        java.lang.Object ref = publishdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publishdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public Builder setPublishdate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        publishdate_ = value;
        
        return this;
      }
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public Builder clearPublishdate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        publishdate_ = getDefaultInstance().getPublishdate();
        
        return this;
      }
      /**
       * <code>optional string publishdate = 11;</code>
       *
       * <pre>
       *新闻发布时间
       * </pre>
       */
      public Builder setPublishdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        publishdate_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewsSentimentUntreated)
    }

    static {
      defaultInstance = new NewsSentimentUntreated(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewsSentimentUntreated)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
