// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.gw.ncps.model;

public final class NewsLogMessage {
  private NewsLogMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LogMessageOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required int32 messageID = 1;
    /**
     * <code>required int32 messageID = 1;</code>
     *
     * <pre>
     * 消息标识符
     * </pre>
     */
    boolean hasMessageID();
    /**
     * <code>required int32 messageID = 1;</code>
     *
     * <pre>
     * 消息标识符
     * </pre>
     */
    int getMessageID();

    // required .Text text = 2;
    /**
     * <code>required .Text text = 2;</code>
     *
     * <pre>
     * 消息结构体
     * </pre>
     */
    boolean hasText();
    /**
     * <code>required .Text text = 2;</code>
     *
     * <pre>
     * 消息结构体
     * </pre>
     */
    com.gw.ncps.model.NewsLogMessage.Text getText();
  }
  /**
   * Protobuf type {@code LogMessage}
   */
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessageLite
      implements LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private LogMessage(boolean noInit) {}

    private static final LogMessage defaultInstance;
    public static LogMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              messageID_ = input.readInt32();
              break;
            }
            case 18: {
              com.gw.ncps.model.NewsLogMessage.Text.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = text_.toBuilder();
              }
              text_ = input.readMessage(com.gw.ncps.model.NewsLogMessage.Text.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(text_);
                text_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<LogMessage> PARSER =
        new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 messageID = 1;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private int messageID_;
    /**
     * <code>required int32 messageID = 1;</code>
     *
     * <pre>
     * 消息标识符
     * </pre>
     */
    public boolean hasMessageID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 messageID = 1;</code>
     *
     * <pre>
     * 消息标识符
     * </pre>
     */
    public int getMessageID() {
      return messageID_;
    }

    // required .Text text = 2;
    public static final int TEXT_FIELD_NUMBER = 2;
    private com.gw.ncps.model.NewsLogMessage.Text text_;
    /**
     * <code>required .Text text = 2;</code>
     *
     * <pre>
     * 消息结构体
     * </pre>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Text text = 2;</code>
     *
     * <pre>
     * 消息结构体
     * </pre>
     */
    public com.gw.ncps.model.NewsLogMessage.Text getText() {
      return text_;
    }

    private void initFields() {
      messageID_ = 0;
      text_ = com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMessageID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getText().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, messageID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, text_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, messageID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, text_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ncps.model.NewsLogMessage.LogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ncps.model.NewsLogMessage.LogMessage, Builder>
        implements com.gw.ncps.model.NewsLogMessage.LogMessageOrBuilder {
      // Construct using com.gw.ncps.model.NewsLogMessage.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ncps.model.NewsLogMessage.LogMessage getDefaultInstanceForType() {
        return com.gw.ncps.model.NewsLogMessage.LogMessage.getDefaultInstance();
      }

      public com.gw.ncps.model.NewsLogMessage.LogMessage build() {
        com.gw.ncps.model.NewsLogMessage.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ncps.model.NewsLogMessage.LogMessage buildPartial() {
        com.gw.ncps.model.NewsLogMessage.LogMessage result = new com.gw.ncps.model.NewsLogMessage.LogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageID_ = messageID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ncps.model.NewsLogMessage.LogMessage other) {
        if (other == com.gw.ncps.model.NewsLogMessage.LogMessage.getDefaultInstance()) return this;
        if (other.hasMessageID()) {
          setMessageID(other.getMessageID());
        }
        if (other.hasText()) {
          mergeText(other.getText());
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMessageID()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        if (!getText().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ncps.model.NewsLogMessage.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ncps.model.NewsLogMessage.LogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 messageID = 1;
      private int messageID_ ;
      /**
       * <code>required int32 messageID = 1;</code>
       *
       * <pre>
       * 消息标识符
       * </pre>
       */
      public boolean hasMessageID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 messageID = 1;</code>
       *
       * <pre>
       * 消息标识符
       * </pre>
       */
      public int getMessageID() {
        return messageID_;
      }
      /**
       * <code>required int32 messageID = 1;</code>
       *
       * <pre>
       * 消息标识符
       * </pre>
       */
      public Builder setMessageID(int value) {
        bitField0_ |= 0x00000001;
        messageID_ = value;
        
        return this;
      }
      /**
       * <code>required int32 messageID = 1;</code>
       *
       * <pre>
       * 消息标识符
       * </pre>
       */
      public Builder clearMessageID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageID_ = 0;
        
        return this;
      }

      // required .Text text = 2;
      private com.gw.ncps.model.NewsLogMessage.Text text_ = com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance();
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public com.gw.ncps.model.NewsLogMessage.Text getText() {
        return text_;
      }
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public Builder setText(com.gw.ncps.model.NewsLogMessage.Text value) {
        if (value == null) {
          throw new NullPointerException();
        }
        text_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public Builder setText(
          com.gw.ncps.model.NewsLogMessage.Text.Builder builderForValue) {
        text_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public Builder mergeText(com.gw.ncps.model.NewsLogMessage.Text value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            text_ != com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance()) {
          text_ =
            com.gw.ncps.model.NewsLogMessage.Text.newBuilder(text_).mergeFrom(value).buildPartial();
        } else {
          text_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Text text = 2;</code>
       *
       * <pre>
       * 消息结构体
       * </pre>
       */
      public Builder clearText() {
        text_ = com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:LogMessage)
    }

    static {
      defaultInstance = new LogMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:LogMessage)
  }

  public interface TextOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string className = 1;
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    boolean hasClassName();
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    java.lang.String getClassName();
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    // required string type = 2;
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    // required string level = 3;
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    java.lang.String getLevel();
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    com.google.protobuf.ByteString
        getLevelBytes();

    // required string times = 4;
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    boolean hasTimes();
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    java.lang.String getTimes();
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    com.google.protobuf.ByteString
        getTimesBytes();

    // repeated string log = 5;
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    java.util.List<java.lang.String>
    getLogList();
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    int getLogCount();
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    java.lang.String getLog(int index);
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getLogBytes(int index);
  }
  /**
   * Protobuf type {@code Text}
   */
  public static final class Text extends
      com.google.protobuf.GeneratedMessageLite
      implements TextOrBuilder {
    // Use Text.newBuilder() to construct.
    private Text(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Text(boolean noInit) {}

    private static final Text defaultInstance;
    public static Text getDefaultInstance() {
      return defaultInstance;
    }

    public Text getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Text(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              className_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              type_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              level_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              times_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                log_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              log_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          log_ = new com.google.protobuf.UnmodifiableLazyStringList(log_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Text> PARSER =
        new com.google.protobuf.AbstractParser<Text>() {
      public Text parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Text(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Text> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string className = 1;
    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private java.lang.Object className_;
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string className = 1;</code>
     *
     * <pre>
     * 日志所在的类  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private java.lang.Object type_;
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 2;</code>
     *
     * <pre>
     * 消息类型：'log':日志, 'stat':统计信息
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string level = 3;
    public static final int LEVEL_FIELD_NUMBER = 3;
    private java.lang.Object level_;
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          level_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string level = 3;</code>
     *
     * <pre>
     * 消息等级
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string times = 4;
    public static final int TIMES_FIELD_NUMBER = 4;
    private java.lang.Object times_;
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    public boolean hasTimes() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    public java.lang.String getTimes() {
      java.lang.Object ref = times_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          times_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string times = 4;</code>
     *
     * <pre>
     * 时间 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTimesBytes() {
      java.lang.Object ref = times_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        times_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string log = 5;
    public static final int LOG_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList log_;
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public java.util.List<java.lang.String>
        getLogList() {
      return log_;
    }
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public int getLogCount() {
      return log_.size();
    }
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public java.lang.String getLog(int index) {
      return log_.get(index);
    }
    /**
     * <code>repeated string log = 5;</code>
     *
     * <pre>
     * 消息内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLogBytes(int index) {
      return log_.getByteString(index);
    }

    private void initFields() {
      className_ = "";
      type_ = "";
      level_ = "";
      times_ = "";
      log_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasClassName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimes()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLevelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTimesBytes());
      }
      for (int i = 0; i < log_.size(); i++) {
        output.writeBytes(5, log_.getByteString(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClassNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTypeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLevelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTimesBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < log_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(log_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLogList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ncps.model.NewsLogMessage.Text parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ncps.model.NewsLogMessage.Text prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code Text}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ncps.model.NewsLogMessage.Text, Builder>
        implements com.gw.ncps.model.NewsLogMessage.TextOrBuilder {
      // Construct using com.gw.ncps.model.NewsLogMessage.Text.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        times_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        log_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ncps.model.NewsLogMessage.Text getDefaultInstanceForType() {
        return com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance();
      }

      public com.gw.ncps.model.NewsLogMessage.Text build() {
        com.gw.ncps.model.NewsLogMessage.Text result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ncps.model.NewsLogMessage.Text buildPartial() {
        com.gw.ncps.model.NewsLogMessage.Text result = new com.gw.ncps.model.NewsLogMessage.Text(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.className_ = className_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.times_ = times_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          log_ = new com.google.protobuf.UnmodifiableLazyStringList(
              log_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.log_ = log_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ncps.model.NewsLogMessage.Text other) {
        if (other == com.gw.ncps.model.NewsLogMessage.Text.getDefaultInstance()) return this;
        if (other.hasClassName()) {
          bitField0_ |= 0x00000001;
          className_ = other.className_;
          
        }
        if (other.hasType()) {
          bitField0_ |= 0x00000002;
          type_ = other.type_;
          
        }
        if (other.hasLevel()) {
          bitField0_ |= 0x00000004;
          level_ = other.level_;
          
        }
        if (other.hasTimes()) {
          bitField0_ |= 0x00000008;
          times_ = other.times_;
          
        }
        if (!other.log_.isEmpty()) {
          if (log_.isEmpty()) {
            log_ = other.log_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureLogIsMutable();
            log_.addAll(other.log_);
          }
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClassName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasTimes()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ncps.model.NewsLogMessage.Text parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ncps.model.NewsLogMessage.Text) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string className = 1;
      private java.lang.Object className_ = "";
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        className_ = value;
        
        return this;
      }
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = getDefaultInstance().getClassName();
        
        return this;
      }
      /**
       * <code>required string className = 1;</code>
       *
       * <pre>
       * 日志所在的类  
       * </pre>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        className_ = value;
        
        return this;
      }

      // required string type = 2;
      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = getDefaultInstance().getType();
        
        return this;
      }
      /**
       * <code>required string type = 2;</code>
       *
       * <pre>
       * 消息类型：'log':日志, 'stat':统计信息
       * </pre>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        type_ = value;
        
        return this;
      }

      // required string level = 3;
      private java.lang.Object level_ = "";
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public java.lang.String getLevel() {
        java.lang.Object ref = level_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          level_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLevelBytes() {
        java.lang.Object ref = level_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          level_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public Builder setLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        level_ = value;
        
        return this;
      }
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        level_ = getDefaultInstance().getLevel();
        
        return this;
      }
      /**
       * <code>required string level = 3;</code>
       *
       * <pre>
       * 消息等级
       * </pre>
       */
      public Builder setLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        level_ = value;
        
        return this;
      }

      // required string times = 4;
      private java.lang.Object times_ = "";
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public boolean hasTimes() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public java.lang.String getTimes() {
        java.lang.Object ref = times_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          times_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTimesBytes() {
        java.lang.Object ref = times_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          times_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public Builder setTimes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        times_ = value;
        
        return this;
      }
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public Builder clearTimes() {
        bitField0_ = (bitField0_ & ~0x00000008);
        times_ = getDefaultInstance().getTimes();
        
        return this;
      }
      /**
       * <code>required string times = 4;</code>
       *
       * <pre>
       * 时间 
       * </pre>
       */
      public Builder setTimesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        times_ = value;
        
        return this;
      }

      // repeated string log = 5;
      private com.google.protobuf.LazyStringList log_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLogIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          log_ = new com.google.protobuf.LazyStringArrayList(log_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public java.util.List<java.lang.String>
          getLogList() {
        return java.util.Collections.unmodifiableList(log_);
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public int getLogCount() {
        return log_.size();
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public java.lang.String getLog(int index) {
        return log_.get(index);
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLogBytes(int index) {
        return log_.getByteString(index);
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder setLog(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLogIsMutable();
        log_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder addLog(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLogIsMutable();
        log_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder addAllLog(
          java.lang.Iterable<java.lang.String> values) {
        ensureLogIsMutable();
        super.addAll(values, log_);
        
        return this;
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder clearLog() {
        log_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        
        return this;
      }
      /**
       * <code>repeated string log = 5;</code>
       *
       * <pre>
       * 消息内容
       * </pre>
       */
      public Builder addLogBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLogIsMutable();
        log_.add(value);
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Text)
    }

    static {
      defaultInstance = new Text(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Text)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
