// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncr.proto

package com.gw.ps.pbbean;

public final class PbNewsClassify {
  private PbNewsClassify() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface NewsClassifyResultOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required int64 newsCode = 1;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID	
     * </pre>
     */
    boolean hasNewsCode();
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID	
     * </pre>
     */
    long getNewsCode();

    // required string result = 2;
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    java.lang.String getResult();
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    com.google.protobuf.ByteString
        getResultBytes();

    // repeated string classNameList = 3;
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    java.util.List<java.lang.String>
    getClassNameListList();
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    int getClassNameListCount();
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    java.lang.String getClassNameList(int index);
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    com.google.protobuf.ByteString
        getClassNameListBytes(int index);

    // required string title = 4;
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    boolean hasTitle();
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    // required string content = 5;
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code NewsClassifyResult}
   */
  public static final class NewsClassifyResult extends
      com.google.protobuf.GeneratedMessageLite
      implements NewsClassifyResultOrBuilder {
    // Use NewsClassifyResult.newBuilder() to construct.
    private NewsClassifyResult(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private NewsClassifyResult(boolean noInit) {}

    private static final NewsClassifyResult defaultInstance;
    public static NewsClassifyResult getDefaultInstance() {
      return defaultInstance;
    }

    public NewsClassifyResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private NewsClassifyResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              result_ = input.readBytes();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                classNameList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000004;
              }
              classNameList_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              title_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(classNameList_);
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<NewsClassifyResult> PARSER =
        new com.google.protobuf.AbstractParser<NewsClassifyResult>() {
      public NewsClassifyResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NewsClassifyResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NewsClassifyResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private long newsCode_;
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID	
     * </pre>
     */
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 newsCode = 1;</code>
     *
     * <pre>
     *新闻ID	
     * </pre>
     */
    public long getNewsCode() {
      return newsCode_;
    }

    // required string result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private java.lang.Object result_;
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          result_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string result = 2;</code>
     *
     * <pre>
     *分类结果	
     * </pre>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated string classNameList = 3;
    public static final int CLASSNAMELIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList classNameList_;
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    public java.util.List<java.lang.String>
        getClassNameListList() {
      return classNameList_;
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    public int getClassNameListCount() {
      return classNameList_.size();
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    public java.lang.String getClassNameList(int index) {
      return classNameList_.get(index);
    }
    /**
     * <code>repeated string classNameList = 3;</code>
     *
     * <pre>
     *分类类别
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClassNameListBytes(int index) {
      return classNameList_.getByteString(index);
    }

    // required string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string title = 4;</code>
     *
     * <pre>
     *标题
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.Object content_;
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 5;</code>
     *
     * <pre>
     *新闻内容
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      newsCode_ = 0L;
      result_ = "";
      classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      title_ = "";
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultBytes());
      }
      for (int i = 0; i < classNameList_.size(); i++) {
        output.writeBytes(3, classNameList_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getContentBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(classNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameListList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code NewsClassifyResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult, Builder>
        implements com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResultOrBuilder {
      // Construct using com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        newsCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult getDefaultInstanceForType() {
        return com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult.getDefaultInstance();
      }

      public com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult build() {
        com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult buildPartial() {
        com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult result = new com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              classNameList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.classNameList_ = classNameList_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult other) {
        if (other == com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasResult()) {
          bitField0_ |= 0x00000002;
          result_ = other.result_;
          
        }
        if (!other.classNameList_.isEmpty()) {
          if (classNameList_.isEmpty()) {
            classNameList_ = other.classNameList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClassNameListIsMutable();
            classNameList_.addAll(other.classNameList_);
          }
          
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000008;
          title_ = other.title_;
          
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.gw.ps.pbbean.PbNewsClassify.NewsClassifyResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 newsCode = 1;
      private long newsCode_ ;
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID	
       * </pre>
       */
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID	
       * </pre>
       */
      public long getNewsCode() {
        return newsCode_;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID	
       * </pre>
       */
      public Builder setNewsCode(long value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        
        return this;
      }
      /**
       * <code>required int64 newsCode = 1;</code>
       *
       * <pre>
       *新闻ID	
       * </pre>
       */
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = 0L;
        
        return this;
      }

      // required string result = 2;
      private java.lang.Object result_ = "";
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        result_ = value;
        
        return this;
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = getDefaultInstance().getResult();
        
        return this;
      }
      /**
       * <code>required string result = 2;</code>
       *
       * <pre>
       *分类结果	
       * </pre>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        result_ = value;
        
        return this;
      }

      // repeated string classNameList = 3;
      private com.google.protobuf.LazyStringList classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.LazyStringArrayList(classNameList_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public java.util.List<java.lang.String>
          getClassNameListList() {
        return java.util.Collections.unmodifiableList(classNameList_);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public int getClassNameListCount() {
        return classNameList_.size();
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public java.lang.String getClassNameList(int index) {
        return classNameList_.get(index);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClassNameListBytes(int index) {
        return classNameList_.getByteString(index);
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public Builder setClassNameList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.set(index, value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public Builder addClassNameList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public Builder addAllClassNameList(
          java.lang.Iterable<java.lang.String> values) {
        ensureClassNameListIsMutable();
        super.addAll(values, classNameList_);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public Builder clearClassNameList() {
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      /**
       * <code>repeated string classNameList = 3;</code>
       *
       * <pre>
       *分类类别
       * </pre>
       */
      public Builder addClassNameListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        
        return this;
      }

      // required string title = 4;
      private java.lang.Object title_ = "";
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        
        return this;
      }
      /**
       * <code>required string title = 4;</code>
       *
       * <pre>
       *标题
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        
        return this;
      }

      // required string content = 5;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        
        return this;
      }
      /**
       * <code>required string content = 5;</code>
       *
       * <pre>
       *新闻内容
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NewsClassifyResult)
    }

    static {
      defaultInstance = new NewsClassifyResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NewsClassifyResult)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
