// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsFilter.proto

package com.gw.protobuf;

public final class NewsFilter {
  private NewsFilter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsFilterDustOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 newsCode = 1;
    boolean hasNewsCode();
    long getNewsCode();
    
    // required string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // required string text = 3;
    boolean hasText();
    String getText();
  }
  public static final class NewsFilterDust extends
      com.google.protobuf.GeneratedMessage
      implements NewsFilterDustOrBuilder {
    // Use NewsFilterDust.newBuilder() to construct.
    private NewsFilterDust(Builder builder) {
      super(builder);
    }
    private NewsFilterDust(boolean noInit) {}
    
    private static final NewsFilterDust defaultInstance;
    public static NewsFilterDust getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsFilterDust getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.protobuf.NewsFilter.internal_static_NewsFilterDust_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.protobuf.NewsFilter.internal_static_NewsFilterDust_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private long newsCode_;
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getNewsCode() {
      return newsCode_;
    }
    
    // required string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      newsCode_ = 0L;
      title_ = "";
      text_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gw.protobuf.NewsFilter.NewsFilterDust parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.protobuf.NewsFilter.NewsFilterDust prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gw.protobuf.NewsFilter.NewsFilterDustOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gw.protobuf.NewsFilter.internal_static_NewsFilterDust_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gw.protobuf.NewsFilter.internal_static_NewsFilterDust_fieldAccessorTable;
      }
      
      // Construct using com.gw.protobuf.NewsFilter.NewsFilterDust.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        newsCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gw.protobuf.NewsFilter.NewsFilterDust.getDescriptor();
      }
      
      public com.gw.protobuf.NewsFilter.NewsFilterDust getDefaultInstanceForType() {
        return com.gw.protobuf.NewsFilter.NewsFilterDust.getDefaultInstance();
      }
      
      public com.gw.protobuf.NewsFilter.NewsFilterDust build() {
        com.gw.protobuf.NewsFilter.NewsFilterDust result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.gw.protobuf.NewsFilter.NewsFilterDust buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.gw.protobuf.NewsFilter.NewsFilterDust result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.gw.protobuf.NewsFilter.NewsFilterDust buildPartial() {
        com.gw.protobuf.NewsFilter.NewsFilterDust result = new com.gw.protobuf.NewsFilter.NewsFilterDust(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gw.protobuf.NewsFilter.NewsFilterDust) {
          return mergeFrom((com.gw.protobuf.NewsFilter.NewsFilterDust)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.gw.protobuf.NewsFilter.NewsFilterDust other) {
        if (other == com.gw.protobuf.NewsFilter.NewsFilterDust.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 newsCode = 1;
      private long newsCode_ ;
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getNewsCode() {
        return newsCode_;
      }
      public Builder setNewsCode(long value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = 0L;
        onChanged();
        return this;
      }
      
      // required string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // required string text = 3;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:NewsFilterDust)
    }
    
    static {
      defaultInstance = new NewsFilterDust(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NewsFilterDust)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewsFilterDust_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewsFilterDust_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020newsFilter.proto\"?\n\016NewsFilterDust\022\020\n\010" +
      "newsCode\030\001 \002(\003\022\r\n\005title\030\002 \002(\t\022\014\n\004text\030\003 " +
      "\002(\tB\021\n\017com.gw.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewsFilterDust_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewsFilterDust_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewsFilterDust_descriptor,
              new java.lang.String[] { "NewsCode", "Title", "Text", },
              com.gw.protobuf.NewsFilter.NewsFilterDust.class,
              com.gw.protobuf.NewsFilter.NewsFilterDust.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
