// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newsSentiResult.proto

package com.gw.protobuf;

public final class NewsSentiResult {
  private NewsSentiResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsSentimentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string newsCode = 1;
    boolean hasNewsCode();
    String getNewsCode();
    
    // optional int32 sentiment = 2;
    boolean hasSentiment();
    int getSentiment();
    
    // optional double posRate = 3;
    boolean hasPosRate();
    double getPosRate();
    
    // optional double negRate = 4;
    boolean hasNegRate();
    double getNegRate();
    
    // optional int64 processTime = 5;
    boolean hasProcessTime();
    long getProcessTime();
    
    // required string title = 6;
    boolean hasTitle();
    String getTitle();
    
    // required string text = 7;
    boolean hasText();
    String getText();
    
    // required string result = 8;
    boolean hasResult();
    String getResult();
    
    // repeated string classNameList = 9;
    java.util.List<String> getClassNameListList();
    int getClassNameListCount();
    String getClassNameList(int index);
    
    // repeated string companyNames = 10;
    java.util.List<String> getCompanyNamesList();
    int getCompanyNamesCount();
    String getCompanyNames(int index);
    
    // optional string accessTime = 11;
    boolean hasAccessTime();
    String getAccessTime();
    
    // optional bool isFiltered = 12;
    boolean hasIsFiltered();
    boolean getIsFiltered();
    
    // optional string typeOf = 13;
    boolean hasTypeOf();
    String getTypeOf();
    
    // optional string publishdate = 14;
    boolean hasPublishdate();
    String getPublishdate();
  }
  public static final class NewsSentiment extends
      com.google.protobuf.GeneratedMessage
      implements NewsSentimentOrBuilder {
    // Use NewsSentiment.newBuilder() to construct.
    private NewsSentiment(Builder builder) {
      super(builder);
    }
    private NewsSentiment(boolean noInit) {}
    
    private static final NewsSentiment defaultInstance;
    public static NewsSentiment getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsSentiment getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gw.protobuf.NewsSentiResult.internal_static_NewsSentiment_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gw.protobuf.NewsSentiResult.internal_static_NewsSentiment_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private java.lang.Object newsCode_;
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNewsCode() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          newsCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNewsCodeBytes() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        newsCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 sentiment = 2;
    public static final int SENTIMENT_FIELD_NUMBER = 2;
    private int sentiment_;
    public boolean hasSentiment() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getSentiment() {
      return sentiment_;
    }
    
    // optional double posRate = 3;
    public static final int POSRATE_FIELD_NUMBER = 3;
    private double posRate_;
    public boolean hasPosRate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getPosRate() {
      return posRate_;
    }
    
    // optional double negRate = 4;
    public static final int NEGRATE_FIELD_NUMBER = 4;
    private double negRate_;
    public boolean hasNegRate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getNegRate() {
      return negRate_;
    }
    
    // optional int64 processTime = 5;
    public static final int PROCESSTIME_FIELD_NUMBER = 5;
    private long processTime_;
    public boolean hasProcessTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getProcessTime() {
      return processTime_;
    }
    
    // required string title = 6;
    public static final int TITLE_FIELD_NUMBER = 6;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string text = 7;
    public static final int TEXT_FIELD_NUMBER = 7;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string result = 8;
    public static final int RESULT_FIELD_NUMBER = 8;
    private java.lang.Object result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          result_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string classNameList = 9;
    public static final int CLASSNAMELIST_FIELD_NUMBER = 9;
    private com.google.protobuf.LazyStringList classNameList_;
    public java.util.List<String>
        getClassNameListList() {
      return classNameList_;
    }
    public int getClassNameListCount() {
      return classNameList_.size();
    }
    public String getClassNameList(int index) {
      return classNameList_.get(index);
    }
    
    // repeated string companyNames = 10;
    public static final int COMPANYNAMES_FIELD_NUMBER = 10;
    private com.google.protobuf.LazyStringList companyNames_;
    public java.util.List<String>
        getCompanyNamesList() {
      return companyNames_;
    }
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    public String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    
    // optional string accessTime = 11;
    public static final int ACCESSTIME_FIELD_NUMBER = 11;
    private java.lang.Object accessTime_;
    public boolean hasAccessTime() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public String getAccessTime() {
      java.lang.Object ref = accessTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          accessTime_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getAccessTimeBytes() {
      java.lang.Object ref = accessTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        accessTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bool isFiltered = 12;
    public static final int ISFILTERED_FIELD_NUMBER = 12;
    private boolean isFiltered_;
    public boolean hasIsFiltered() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public boolean getIsFiltered() {
      return isFiltered_;
    }
    
    // optional string typeOf = 13;
    public static final int TYPEOF_FIELD_NUMBER = 13;
    private java.lang.Object typeOf_;
    public boolean hasTypeOf() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getTypeOf() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          typeOf_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeOfBytes() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        typeOf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string publishdate = 14;
    public static final int PUBLISHDATE_FIELD_NUMBER = 14;
    private java.lang.Object publishdate_;
    public boolean hasPublishdate() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getPublishdate() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          publishdate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPublishdateBytes() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        publishdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      newsCode_ = "";
      sentiment_ = 0;
      posRate_ = 0D;
      negRate_ = 0D;
      processTime_ = 0L;
      title_ = "";
      text_ = "";
      result_ = "";
      classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      accessTime_ = "";
      isFiltered_ = false;
      typeOf_ = "";
      publishdate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasText()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, sentiment_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, posRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, negRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, processTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getResultBytes());
      }
      for (int i = 0; i < classNameList_.size(); i++) {
        output.writeBytes(9, classNameList_.getByteString(i));
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(10, companyNames_.getByteString(i));
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(11, getAccessTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBool(12, isFiltered_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(13, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(14, getPublishdateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, sentiment_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, posRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, negRate_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, processTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getTitleBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTextBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getResultBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(classNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameListList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getAccessTimeBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(12, isFiltered_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(14, getPublishdateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.gw.protobuf.NewsSentiResult.NewsSentiment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.gw.protobuf.NewsSentiResult.NewsSentiment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.gw.protobuf.NewsSentiResult.NewsSentimentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.gw.protobuf.NewsSentiResult.internal_static_NewsSentiment_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.gw.protobuf.NewsSentiResult.internal_static_NewsSentiment_fieldAccessorTable;
      }
      
      // Construct using com.gw.protobuf.NewsSentiResult.NewsSentiment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        newsCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sentiment_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        posRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        negRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        processTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        accessTime_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        isFiltered_ = false;
        bitField0_ = (bitField0_ & ~0x00000800);
        typeOf_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        publishdate_ = "";
        bitField0_ = (bitField0_ & ~0x00002000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.gw.protobuf.NewsSentiResult.NewsSentiment.getDescriptor();
      }
      
      public com.gw.protobuf.NewsSentiResult.NewsSentiment getDefaultInstanceForType() {
        return com.gw.protobuf.NewsSentiResult.NewsSentiment.getDefaultInstance();
      }
      
      public com.gw.protobuf.NewsSentiResult.NewsSentiment build() {
        com.gw.protobuf.NewsSentiResult.NewsSentiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.gw.protobuf.NewsSentiResult.NewsSentiment buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.gw.protobuf.NewsSentiResult.NewsSentiment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.gw.protobuf.NewsSentiResult.NewsSentiment buildPartial() {
        com.gw.protobuf.NewsSentiResult.NewsSentiment result = new com.gw.protobuf.NewsSentiResult.NewsSentiment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sentiment_ = sentiment_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.posRate_ = posRate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.negRate_ = negRate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.processTime_ = processTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.result_ = result_;
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              classNameList_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.classNameList_ = classNameList_;
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.companyNames_ = companyNames_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000100;
        }
        result.accessTime_ = accessTime_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000200;
        }
        result.isFiltered_ = isFiltered_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00000400;
        }
        result.typeOf_ = typeOf_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00000800;
        }
        result.publishdate_ = publishdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.gw.protobuf.NewsSentiResult.NewsSentiment) {
          return mergeFrom((com.gw.protobuf.NewsSentiResult.NewsSentiment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.gw.protobuf.NewsSentiResult.NewsSentiment other) {
        if (other == com.gw.protobuf.NewsSentiResult.NewsSentiment.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasSentiment()) {
          setSentiment(other.getSentiment());
        }
        if (other.hasPosRate()) {
          setPosRate(other.getPosRate());
        }
        if (other.hasNegRate()) {
          setNegRate(other.getNegRate());
        }
        if (other.hasProcessTime()) {
          setProcessTime(other.getProcessTime());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (!other.classNameList_.isEmpty()) {
          if (classNameList_.isEmpty()) {
            classNameList_ = other.classNameList_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureClassNameListIsMutable();
            classNameList_.addAll(other.classNameList_);
          }
          onChanged();
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          onChanged();
        }
        if (other.hasAccessTime()) {
          setAccessTime(other.getAccessTime());
        }
        if (other.hasIsFiltered()) {
          setIsFiltered(other.getIsFiltered());
        }
        if (other.hasTypeOf()) {
          setTypeOf(other.getTypeOf());
        }
        if (other.hasPublishdate()) {
          setPublishdate(other.getPublishdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasText()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sentiment_ = input.readInt32();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              posRate_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              negRate_ = input.readDouble();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              processTime_ = input.readInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              title_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              text_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              result_ = input.readBytes();
              break;
            }
            case 74: {
              ensureClassNameListIsMutable();
              classNameList_.add(input.readBytes());
              break;
            }
            case 82: {
              ensureCompanyNamesIsMutable();
              companyNames_.add(input.readBytes());
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              accessTime_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              isFiltered_ = input.readBool();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              typeOf_ = input.readBytes();
              break;
            }
            case 114: {
              bitField0_ |= 0x00002000;
              publishdate_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string newsCode = 1;
      private java.lang.Object newsCode_ = "";
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNewsCode() {
        java.lang.Object ref = newsCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          newsCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNewsCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = getDefaultInstance().getNewsCode();
        onChanged();
        return this;
      }
      void setNewsCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
      }
      
      // optional int32 sentiment = 2;
      private int sentiment_ ;
      public boolean hasSentiment() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getSentiment() {
        return sentiment_;
      }
      public Builder setSentiment(int value) {
        bitField0_ |= 0x00000002;
        sentiment_ = value;
        onChanged();
        return this;
      }
      public Builder clearSentiment() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sentiment_ = 0;
        onChanged();
        return this;
      }
      
      // optional double posRate = 3;
      private double posRate_ ;
      public boolean hasPosRate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getPosRate() {
        return posRate_;
      }
      public Builder setPosRate(double value) {
        bitField0_ |= 0x00000004;
        posRate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPosRate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        posRate_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double negRate = 4;
      private double negRate_ ;
      public boolean hasNegRate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getNegRate() {
        return negRate_;
      }
      public Builder setNegRate(double value) {
        bitField0_ |= 0x00000008;
        negRate_ = value;
        onChanged();
        return this;
      }
      public Builder clearNegRate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        negRate_ = 0D;
        onChanged();
        return this;
      }
      
      // optional int64 processTime = 5;
      private long processTime_ ;
      public boolean hasProcessTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getProcessTime() {
        return processTime_;
      }
      public Builder setProcessTime(long value) {
        bitField0_ |= 0x00000010;
        processTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcessTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        processTime_ = 0L;
        onChanged();
        return this;
      }
      
      // required string title = 6;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000020);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000020;
        title_ = value;
        onChanged();
      }
      
      // required string text = 7;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        text_ = value;
        onChanged();
      }
      
      // required string result = 8;
      private java.lang.Object result_ = "";
      public boolean hasResult() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResult(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000080);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      void setResult(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        result_ = value;
        onChanged();
      }
      
      // repeated string classNameList = 9;
      private com.google.protobuf.LazyStringList classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameListIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          classNameList_ = new com.google.protobuf.LazyStringArrayList(classNameList_);
          bitField0_ |= 0x00000100;
         }
      }
      public java.util.List<String>
          getClassNameListList() {
        return java.util.Collections.unmodifiableList(classNameList_);
      }
      public int getClassNameListCount() {
        return classNameList_.size();
      }
      public String getClassNameList(int index) {
        return classNameList_.get(index);
      }
      public Builder setClassNameList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addClassNameList(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllClassNameList(
          java.lang.Iterable<String> values) {
        ensureClassNameListIsMutable();
        super.addAll(values, classNameList_);
        onChanged();
        return this;
      }
      public Builder clearClassNameList() {
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      void addClassNameList(com.google.protobuf.ByteString value) {
        ensureClassNameListIsMutable();
        classNameList_.add(value);
        onChanged();
      }
      
      // repeated string companyNames = 10;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000200) == 0x00000200)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000200;
         }
      }
      public java.util.List<String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      public String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      public Builder setCompanyNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCompanyNames(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCompanyNames(
          java.lang.Iterable<String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        onChanged();
        return this;
      }
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
        return this;
      }
      void addCompanyNames(com.google.protobuf.ByteString value) {
        ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
      }
      
      // optional string accessTime = 11;
      private java.lang.Object accessTime_ = "";
      public boolean hasAccessTime() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getAccessTime() {
        java.lang.Object ref = accessTime_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          accessTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setAccessTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        accessTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccessTime() {
        bitField0_ = (bitField0_ & ~0x00000400);
        accessTime_ = getDefaultInstance().getAccessTime();
        onChanged();
        return this;
      }
      void setAccessTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        accessTime_ = value;
        onChanged();
      }
      
      // optional bool isFiltered = 12;
      private boolean isFiltered_ ;
      public boolean hasIsFiltered() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public boolean getIsFiltered() {
        return isFiltered_;
      }
      public Builder setIsFiltered(boolean value) {
        bitField0_ |= 0x00000800;
        isFiltered_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsFiltered() {
        bitField0_ = (bitField0_ & ~0x00000800);
        isFiltered_ = false;
        onChanged();
        return this;
      }
      
      // optional string typeOf = 13;
      private java.lang.Object typeOf_ = "";
      public boolean hasTypeOf() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getTypeOf() {
        java.lang.Object ref = typeOf_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          typeOf_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTypeOf(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        typeOf_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeOf() {
        bitField0_ = (bitField0_ & ~0x00001000);
        typeOf_ = getDefaultInstance().getTypeOf();
        onChanged();
        return this;
      }
      void setTypeOf(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        typeOf_ = value;
        onChanged();
      }
      
      // optional string publishdate = 14;
      private java.lang.Object publishdate_ = "";
      public boolean hasPublishdate() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      public String getPublishdate() {
        java.lang.Object ref = publishdate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          publishdate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPublishdate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00002000;
        publishdate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublishdate() {
        bitField0_ = (bitField0_ & ~0x00002000);
        publishdate_ = getDefaultInstance().getPublishdate();
        onChanged();
        return this;
      }
      void setPublishdate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00002000;
        publishdate_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:NewsSentiment)
    }
    
    static {
      defaultInstance = new NewsSentiment(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NewsSentiment)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewsSentiment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewsSentiment_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025newsSentiResult.proto\"\222\002\n\rNewsSentimen" +
      "t\022\020\n\010newsCode\030\001 \002(\t\022\021\n\tsentiment\030\002 \001(\005\022\017" +
      "\n\007posRate\030\003 \001(\001\022\017\n\007negRate\030\004 \001(\001\022\023\n\013proc" +
      "essTime\030\005 \001(\003\022\r\n\005title\030\006 \002(\t\022\014\n\004text\030\007 \002" +
      "(\t\022\016\n\006result\030\010 \002(\t\022\025\n\rclassNameList\030\t \003(" +
      "\t\022\024\n\014companyNames\030\n \003(\t\022\022\n\naccessTime\030\013 " +
      "\001(\t\022\022\n\nisFiltered\030\014 \001(\010\022\016\n\006typeOf\030\r \001(\t\022" +
      "\023\n\013publishdate\030\016 \001(\tB\021\n\017com.gw.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewsSentiment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewsSentiment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewsSentiment_descriptor,
              new java.lang.String[] { "NewsCode", "Sentiment", "PosRate", "NegRate", "ProcessTime", "Title", "Text", "Result", "ClassNameList", "CompanyNames", "AccessTime", "IsFiltered", "TypeOf", "Publishdate", },
              com.gw.protobuf.NewsSentiResult.NewsSentiment.class,
              com.gw.protobuf.NewsSentiResult.NewsSentiment.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
