// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ncr.proto

package classify.protobuf;

public final class NewsClassifyResultProto {
  private NewsClassifyResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsClassifyResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 newsCode = 1;
    boolean hasNewsCode();
    long getNewsCode();
    
    // required string result = 2;
    boolean hasResult();
    String getResult();
    
    // repeated string classNameList = 3;
    java.util.List<String> getClassNameListList();
    int getClassNameListCount();
    String getClassNameList(int index);
    
    // required string title = 4;
    boolean hasTitle();
    String getTitle();
    
    // required string content = 5;
    boolean hasContent();
    String getContent();
    
    // repeated string companyNames = 6;
    java.util.List<String> getCompanyNamesList();
    int getCompanyNamesCount();
    String getCompanyNames(int index);
  }
  public static final class NewsClassifyResult extends
      com.google.protobuf.GeneratedMessage
      implements NewsClassifyResultOrBuilder {
    // Use NewsClassifyResult.newBuilder() to construct.
    private NewsClassifyResult(Builder builder) {
      super(builder);
    }
    private NewsClassifyResult(boolean noInit) {}
    
    private static final NewsClassifyResult defaultInstance;
    public static NewsClassifyResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsClassifyResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return classify.protobuf.NewsClassifyResultProto.internal_static_NewsClassifyResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return classify.protobuf.NewsClassifyResultProto.internal_static_NewsClassifyResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private long newsCode_;
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getNewsCode() {
      return newsCode_;
    }
    
    // required string result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private java.lang.Object result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          result_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string classNameList = 3;
    public static final int CLASSNAMELIST_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList classNameList_;
    public java.util.List<String>
        getClassNameListList() {
      return classNameList_;
    }
    public int getClassNameListCount() {
      return classNameList_.size();
    }
    public String getClassNameList(int index) {
      return classNameList_.get(index);
    }
    
    // required string title = 4;
    public static final int TITLE_FIELD_NUMBER = 4;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private java.lang.Object content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          content_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string companyNames = 6;
    public static final int COMPANYNAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList companyNames_;
    public java.util.List<String>
        getCompanyNamesList() {
      return companyNames_;
    }
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    public String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    
    private void initFields() {
      newsCode_ = 0L;
      result_ = "";
      classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      title_ = "";
      content_ = "";
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitle()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getResultBytes());
      }
      for (int i = 0; i < classNameList_.size(); i++) {
        output.writeBytes(3, classNameList_.getByteString(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getContentBytes());
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(6, companyNames_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, newsCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getResultBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < classNameList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(classNameList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getClassNameListList().size();
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTitleBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static classify.protobuf.NewsClassifyResultProto.NewsClassifyResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(classify.protobuf.NewsClassifyResultProto.NewsClassifyResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements classify.protobuf.NewsClassifyResultProto.NewsClassifyResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return classify.protobuf.NewsClassifyResultProto.internal_static_NewsClassifyResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return classify.protobuf.NewsClassifyResultProto.internal_static_NewsClassifyResult_fieldAccessorTable;
      }
      
      // Construct using classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        newsCode_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.getDescriptor();
      }
      
      public classify.protobuf.NewsClassifyResultProto.NewsClassifyResult getDefaultInstanceForType() {
        return classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.getDefaultInstance();
      }
      
      public classify.protobuf.NewsClassifyResultProto.NewsClassifyResult build() {
        classify.protobuf.NewsClassifyResultProto.NewsClassifyResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private classify.protobuf.NewsClassifyResultProto.NewsClassifyResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        classify.protobuf.NewsClassifyResultProto.NewsClassifyResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public classify.protobuf.NewsClassifyResultProto.NewsClassifyResult buildPartial() {
        classify.protobuf.NewsClassifyResultProto.NewsClassifyResult result = new classify.protobuf.NewsClassifyResultProto.NewsClassifyResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.result_ = result_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.UnmodifiableLazyStringList(
              classNameList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.classNameList_ = classNameList_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.companyNames_ = companyNames_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof classify.protobuf.NewsClassifyResultProto.NewsClassifyResult) {
          return mergeFrom((classify.protobuf.NewsClassifyResultProto.NewsClassifyResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(classify.protobuf.NewsClassifyResultProto.NewsClassifyResult other) {
        if (other == classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (!other.classNameList_.isEmpty()) {
          if (classNameList_.isEmpty()) {
            classNameList_ = other.classNameList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClassNameListIsMutable();
            classNameList_.addAll(other.classNameList_);
          }
          onChanged();
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        if (!hasResult()) {
          
          return false;
        }
        if (!hasTitle()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              result_ = input.readBytes();
              break;
            }
            case 26: {
              ensureClassNameListIsMutable();
              classNameList_.add(input.readBytes());
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              title_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              content_ = input.readBytes();
              break;
            }
            case 50: {
              ensureCompanyNamesIsMutable();
              companyNames_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 newsCode = 1;
      private long newsCode_ ;
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getNewsCode() {
        return newsCode_;
      }
      public Builder setNewsCode(long value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = 0L;
        onChanged();
        return this;
      }
      
      // required string result = 2;
      private java.lang.Object result_ = "";
      public boolean hasResult() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setResult(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      void setResult(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        result_ = value;
        onChanged();
      }
      
      // repeated string classNameList = 3;
      private com.google.protobuf.LazyStringList classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureClassNameListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          classNameList_ = new com.google.protobuf.LazyStringArrayList(classNameList_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getClassNameListList() {
        return java.util.Collections.unmodifiableList(classNameList_);
      }
      public int getClassNameListCount() {
        return classNameList_.size();
      }
      public String getClassNameList(int index) {
        return classNameList_.get(index);
      }
      public Builder setClassNameList(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addClassNameList(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureClassNameListIsMutable();
        classNameList_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllClassNameList(
          java.lang.Iterable<String> values) {
        ensureClassNameListIsMutable();
        super.addAll(values, classNameList_);
        onChanged();
        return this;
      }
      public Builder clearClassNameList() {
        classNameList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addClassNameList(com.google.protobuf.ByteString value) {
        ensureClassNameListIsMutable();
        classNameList_.add(value);
        onChanged();
      }
      
      // required string title = 4;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        title_ = value;
        onChanged();
      }
      
      // required string content = 5;
      private java.lang.Object content_ = "";
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setContent(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      void setContent(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
      }
      
      // repeated string companyNames = 6;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      public String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      public Builder setCompanyNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCompanyNames(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCompanyNames(
          java.lang.Iterable<String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        onChanged();
        return this;
      }
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      void addCompanyNames(com.google.protobuf.ByteString value) {
        ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:NewsClassifyResult)
    }
    
    static {
      defaultInstance = new NewsClassifyResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NewsClassifyResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewsClassifyResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewsClassifyResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tncr.proto\"\203\001\n\022NewsClassifyResult\022\020\n\010ne" +
      "wsCode\030\001 \002(\003\022\016\n\006result\030\002 \002(\t\022\025\n\rclassNam" +
      "eList\030\003 \003(\t\022\r\n\005title\030\004 \002(\t\022\017\n\007content\030\005 " +
      "\002(\t\022\024\n\014companyNames\030\006 \003(\tB,\n\021classify.pr" +
      "otobufB\027NewsClassifyResultProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewsClassifyResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewsClassifyResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewsClassifyResult_descriptor,
              new java.lang.String[] { "NewsCode", "Result", "ClassNameList", "Title", "Content", "CompanyNames", },
              classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.class,
              classify.protobuf.NewsClassifyResultProto.NewsClassifyResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
