// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NewsSentimentUntreated.proto

package classify.protobuf;

public final class PbNewsSentimentUntreated {
  private PbNewsSentimentUntreated() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NewsSentimentUntreatedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string newsCode = 1;
    boolean hasNewsCode();
    String getNewsCode();
    
    // optional string title = 2;
    boolean hasTitle();
    String getTitle();
    
    // optional string text = 3;
    boolean hasText();
    String getText();
    
    // optional string newsType = 4;
    boolean hasNewsType();
    String getNewsType();
    
    // repeated string companyIds = 5;
    java.util.List<String> getCompanyIdsList();
    int getCompanyIdsCount();
    String getCompanyIds(int index);
    
    // repeated string companyNames = 6;
    java.util.List<String> getCompanyNamesList();
    int getCompanyNamesCount();
    String getCompanyNames(int index);
    
    // repeated string industryIds = 7;
    java.util.List<String> getIndustryIdsList();
    int getIndustryIdsCount();
    String getIndustryIds(int index);
    
    // repeated string industryNames = 8;
    java.util.List<String> getIndustryNamesList();
    int getIndustryNamesCount();
    String getIndustryNames(int index);
    
    // optional string entryDate = 9;
    boolean hasEntryDate();
    String getEntryDate();
    
    // optional string typeOf = 10;
    boolean hasTypeOf();
    String getTypeOf();
    
    // optional string publishdate = 11;
    boolean hasPublishdate();
    String getPublishdate();
  }
  public static final class NewsSentimentUntreated extends
      com.google.protobuf.GeneratedMessage
      implements NewsSentimentUntreatedOrBuilder {
    // Use NewsSentimentUntreated.newBuilder() to construct.
    private NewsSentimentUntreated(Builder builder) {
      super(builder);
    }
    private NewsSentimentUntreated(boolean noInit) {}
    
    private static final NewsSentimentUntreated defaultInstance;
    public static NewsSentimentUntreated getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewsSentimentUntreated getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return classify.protobuf.PbNewsSentimentUntreated.internal_static_NewsSentimentUntreated_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return classify.protobuf.PbNewsSentimentUntreated.internal_static_NewsSentimentUntreated_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string newsCode = 1;
    public static final int NEWSCODE_FIELD_NUMBER = 1;
    private java.lang.Object newsCode_;
    public boolean hasNewsCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNewsCode() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          newsCode_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNewsCodeBytes() {
      java.lang.Object ref = newsCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        newsCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string title = 2;
    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          title_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string text = 3;
    public static final int TEXT_FIELD_NUMBER = 3;
    private java.lang.Object text_;
    public boolean hasText() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          text_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string newsType = 4;
    public static final int NEWSTYPE_FIELD_NUMBER = 4;
    private java.lang.Object newsType_;
    public boolean hasNewsType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getNewsType() {
      java.lang.Object ref = newsType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          newsType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNewsTypeBytes() {
      java.lang.Object ref = newsType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        newsType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string companyIds = 5;
    public static final int COMPANYIDS_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList companyIds_;
    public java.util.List<String>
        getCompanyIdsList() {
      return companyIds_;
    }
    public int getCompanyIdsCount() {
      return companyIds_.size();
    }
    public String getCompanyIds(int index) {
      return companyIds_.get(index);
    }
    
    // repeated string companyNames = 6;
    public static final int COMPANYNAMES_FIELD_NUMBER = 6;
    private com.google.protobuf.LazyStringList companyNames_;
    public java.util.List<String>
        getCompanyNamesList() {
      return companyNames_;
    }
    public int getCompanyNamesCount() {
      return companyNames_.size();
    }
    public String getCompanyNames(int index) {
      return companyNames_.get(index);
    }
    
    // repeated string industryIds = 7;
    public static final int INDUSTRYIDS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList industryIds_;
    public java.util.List<String>
        getIndustryIdsList() {
      return industryIds_;
    }
    public int getIndustryIdsCount() {
      return industryIds_.size();
    }
    public String getIndustryIds(int index) {
      return industryIds_.get(index);
    }
    
    // repeated string industryNames = 8;
    public static final int INDUSTRYNAMES_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList industryNames_;
    public java.util.List<String>
        getIndustryNamesList() {
      return industryNames_;
    }
    public int getIndustryNamesCount() {
      return industryNames_.size();
    }
    public String getIndustryNames(int index) {
      return industryNames_.get(index);
    }
    
    // optional string entryDate = 9;
    public static final int ENTRYDATE_FIELD_NUMBER = 9;
    private java.lang.Object entryDate_;
    public boolean hasEntryDate() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getEntryDate() {
      java.lang.Object ref = entryDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          entryDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getEntryDateBytes() {
      java.lang.Object ref = entryDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        entryDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string typeOf = 10;
    public static final int TYPEOF_FIELD_NUMBER = 10;
    private java.lang.Object typeOf_;
    public boolean hasTypeOf() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getTypeOf() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          typeOf_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeOfBytes() {
      java.lang.Object ref = typeOf_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        typeOf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string publishdate = 11;
    public static final int PUBLISHDATE_FIELD_NUMBER = 11;
    private java.lang.Object publishdate_;
    public boolean hasPublishdate() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getPublishdate() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          publishdate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPublishdateBytes() {
      java.lang.Object ref = publishdate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        publishdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      newsCode_ = "";
      title_ = "";
      text_ = "";
      newsType_ = "";
      companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      entryDate_ = "";
      typeOf_ = "";
      publishdate_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNewsCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNewsTypeBytes());
      }
      for (int i = 0; i < companyIds_.size(); i++) {
        output.writeBytes(5, companyIds_.getByteString(i));
      }
      for (int i = 0; i < companyNames_.size(); i++) {
        output.writeBytes(6, companyNames_.getByteString(i));
      }
      for (int i = 0; i < industryIds_.size(); i++) {
        output.writeBytes(7, industryIds_.getByteString(i));
      }
      for (int i = 0; i < industryNames_.size(); i++) {
        output.writeBytes(8, industryNames_.getByteString(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(9, getEntryDateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(10, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(11, getPublishdateBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNewsCodeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNewsTypeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyIds_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < companyNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(companyNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getCompanyNamesList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < industryIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(industryIds_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIndustryIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < industryNames_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(industryNames_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIndustryNamesList().size();
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getEntryDateBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getTypeOfBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getPublishdateBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreatedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return classify.protobuf.PbNewsSentimentUntreated.internal_static_NewsSentimentUntreated_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return classify.protobuf.PbNewsSentimentUntreated.internal_static_NewsSentimentUntreated_fieldAccessorTable;
      }
      
      // Construct using classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        newsCode_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        newsType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        entryDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        typeOf_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        publishdate_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.getDescriptor();
      }
      
      public classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated getDefaultInstanceForType() {
        return classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.getDefaultInstance();
      }
      
      public classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated build() {
        classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated buildPartial() {
        classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated result = new classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.newsCode_ = newsCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.newsType_ = newsType_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          companyIds_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyIds_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.companyIds_ = companyIds_;
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              companyNames_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.companyNames_ = companyNames_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          industryIds_ = new com.google.protobuf.UnmodifiableLazyStringList(
              industryIds_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.industryIds_ = industryIds_;
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          industryNames_ = new com.google.protobuf.UnmodifiableLazyStringList(
              industryNames_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.industryNames_ = industryNames_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000010;
        }
        result.entryDate_ = entryDate_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000020;
        }
        result.typeOf_ = typeOf_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000040;
        }
        result.publishdate_ = publishdate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated) {
          return mergeFrom((classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated other) {
        if (other == classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.getDefaultInstance()) return this;
        if (other.hasNewsCode()) {
          setNewsCode(other.getNewsCode());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasText()) {
          setText(other.getText());
        }
        if (other.hasNewsType()) {
          setNewsType(other.getNewsType());
        }
        if (!other.companyIds_.isEmpty()) {
          if (companyIds_.isEmpty()) {
            companyIds_ = other.companyIds_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCompanyIdsIsMutable();
            companyIds_.addAll(other.companyIds_);
          }
          onChanged();
        }
        if (!other.companyNames_.isEmpty()) {
          if (companyNames_.isEmpty()) {
            companyNames_ = other.companyNames_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureCompanyNamesIsMutable();
            companyNames_.addAll(other.companyNames_);
          }
          onChanged();
        }
        if (!other.industryIds_.isEmpty()) {
          if (industryIds_.isEmpty()) {
            industryIds_ = other.industryIds_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureIndustryIdsIsMutable();
            industryIds_.addAll(other.industryIds_);
          }
          onChanged();
        }
        if (!other.industryNames_.isEmpty()) {
          if (industryNames_.isEmpty()) {
            industryNames_ = other.industryNames_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureIndustryNamesIsMutable();
            industryNames_.addAll(other.industryNames_);
          }
          onChanged();
        }
        if (other.hasEntryDate()) {
          setEntryDate(other.getEntryDate());
        }
        if (other.hasTypeOf()) {
          setTypeOf(other.getTypeOf());
        }
        if (other.hasPublishdate()) {
          setPublishdate(other.getPublishdate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNewsCode()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              newsCode_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              title_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              text_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              newsType_ = input.readBytes();
              break;
            }
            case 42: {
              ensureCompanyIdsIsMutable();
              companyIds_.add(input.readBytes());
              break;
            }
            case 50: {
              ensureCompanyNamesIsMutable();
              companyNames_.add(input.readBytes());
              break;
            }
            case 58: {
              ensureIndustryIdsIsMutable();
              industryIds_.add(input.readBytes());
              break;
            }
            case 66: {
              ensureIndustryNamesIsMutable();
              industryNames_.add(input.readBytes());
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              entryDate_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              typeOf_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              publishdate_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string newsCode = 1;
      private java.lang.Object newsCode_ = "";
      public boolean hasNewsCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNewsCode() {
        java.lang.Object ref = newsCode_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          newsCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNewsCode(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewsCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        newsCode_ = getDefaultInstance().getNewsCode();
        onChanged();
        return this;
      }
      void setNewsCode(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        newsCode_ = value;
        onChanged();
      }
      
      // optional string title = 2;
      private java.lang.Object title_ = "";
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitle(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      void setTitle(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
      }
      
      // optional string text = 3;
      private java.lang.Object text_ = "";
      public boolean hasText() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setText(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
        return this;
      }
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      void setText(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        text_ = value;
        onChanged();
      }
      
      // optional string newsType = 4;
      private java.lang.Object newsType_ = "";
      public boolean hasNewsType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getNewsType() {
        java.lang.Object ref = newsType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          newsType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNewsType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        newsType_ = value;
        onChanged();
        return this;
      }
      public Builder clearNewsType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        newsType_ = getDefaultInstance().getNewsType();
        onChanged();
        return this;
      }
      void setNewsType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        newsType_ = value;
        onChanged();
      }
      
      // repeated string companyIds = 5;
      private com.google.protobuf.LazyStringList companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyIdsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          companyIds_ = new com.google.protobuf.LazyStringArrayList(companyIds_);
          bitField0_ |= 0x00000010;
         }
      }
      public java.util.List<String>
          getCompanyIdsList() {
        return java.util.Collections.unmodifiableList(companyIds_);
      }
      public int getCompanyIdsCount() {
        return companyIds_.size();
      }
      public String getCompanyIds(int index) {
        return companyIds_.get(index);
      }
      public Builder setCompanyIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyIdsIsMutable();
        companyIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCompanyIds(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyIdsIsMutable();
        companyIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCompanyIds(
          java.lang.Iterable<String> values) {
        ensureCompanyIdsIsMutable();
        super.addAll(values, companyIds_);
        onChanged();
        return this;
      }
      public Builder clearCompanyIds() {
        companyIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      void addCompanyIds(com.google.protobuf.ByteString value) {
        ensureCompanyIdsIsMutable();
        companyIds_.add(value);
        onChanged();
      }
      
      // repeated string companyNames = 6;
      private com.google.protobuf.LazyStringList companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureCompanyNamesIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          companyNames_ = new com.google.protobuf.LazyStringArrayList(companyNames_);
          bitField0_ |= 0x00000020;
         }
      }
      public java.util.List<String>
          getCompanyNamesList() {
        return java.util.Collections.unmodifiableList(companyNames_);
      }
      public int getCompanyNamesCount() {
        return companyNames_.size();
      }
      public String getCompanyNames(int index) {
        return companyNames_.get(index);
      }
      public Builder setCompanyNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addCompanyNames(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllCompanyNames(
          java.lang.Iterable<String> values) {
        ensureCompanyNamesIsMutable();
        super.addAll(values, companyNames_);
        onChanged();
        return this;
      }
      public Builder clearCompanyNames() {
        companyNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      void addCompanyNames(com.google.protobuf.ByteString value) {
        ensureCompanyNamesIsMutable();
        companyNames_.add(value);
        onChanged();
      }
      
      // repeated string industryIds = 7;
      private com.google.protobuf.LazyStringList industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndustryIdsIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          industryIds_ = new com.google.protobuf.LazyStringArrayList(industryIds_);
          bitField0_ |= 0x00000040;
         }
      }
      public java.util.List<String>
          getIndustryIdsList() {
        return java.util.Collections.unmodifiableList(industryIds_);
      }
      public int getIndustryIdsCount() {
        return industryIds_.size();
      }
      public String getIndustryIds(int index) {
        return industryIds_.get(index);
      }
      public Builder setIndustryIds(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryIdsIsMutable();
        industryIds_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addIndustryIds(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryIdsIsMutable();
        industryIds_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllIndustryIds(
          java.lang.Iterable<String> values) {
        ensureIndustryIdsIsMutable();
        super.addAll(values, industryIds_);
        onChanged();
        return this;
      }
      public Builder clearIndustryIds() {
        industryIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      void addIndustryIds(com.google.protobuf.ByteString value) {
        ensureIndustryIdsIsMutable();
        industryIds_.add(value);
        onChanged();
      }
      
      // repeated string industryNames = 8;
      private com.google.protobuf.LazyStringList industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIndustryNamesIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          industryNames_ = new com.google.protobuf.LazyStringArrayList(industryNames_);
          bitField0_ |= 0x00000080;
         }
      }
      public java.util.List<String>
          getIndustryNamesList() {
        return java.util.Collections.unmodifiableList(industryNames_);
      }
      public int getIndustryNamesCount() {
        return industryNames_.size();
      }
      public String getIndustryNames(int index) {
        return industryNames_.get(index);
      }
      public Builder setIndustryNames(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryNamesIsMutable();
        industryNames_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addIndustryNames(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIndustryNamesIsMutable();
        industryNames_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllIndustryNames(
          java.lang.Iterable<String> values) {
        ensureIndustryNamesIsMutable();
        super.addAll(values, industryNames_);
        onChanged();
        return this;
      }
      public Builder clearIndustryNames() {
        industryNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      void addIndustryNames(com.google.protobuf.ByteString value) {
        ensureIndustryNamesIsMutable();
        industryNames_.add(value);
        onChanged();
      }
      
      // optional string entryDate = 9;
      private java.lang.Object entryDate_ = "";
      public boolean hasEntryDate() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getEntryDate() {
        java.lang.Object ref = entryDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          entryDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setEntryDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        entryDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearEntryDate() {
        bitField0_ = (bitField0_ & ~0x00000100);
        entryDate_ = getDefaultInstance().getEntryDate();
        onChanged();
        return this;
      }
      void setEntryDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        entryDate_ = value;
        onChanged();
      }
      
      // optional string typeOf = 10;
      private java.lang.Object typeOf_ = "";
      public boolean hasTypeOf() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getTypeOf() {
        java.lang.Object ref = typeOf_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          typeOf_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTypeOf(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        typeOf_ = value;
        onChanged();
        return this;
      }
      public Builder clearTypeOf() {
        bitField0_ = (bitField0_ & ~0x00000200);
        typeOf_ = getDefaultInstance().getTypeOf();
        onChanged();
        return this;
      }
      void setTypeOf(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        typeOf_ = value;
        onChanged();
      }
      
      // optional string publishdate = 11;
      private java.lang.Object publishdate_ = "";
      public boolean hasPublishdate() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getPublishdate() {
        java.lang.Object ref = publishdate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          publishdate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPublishdate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        publishdate_ = value;
        onChanged();
        return this;
      }
      public Builder clearPublishdate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        publishdate_ = getDefaultInstance().getPublishdate();
        onChanged();
        return this;
      }
      void setPublishdate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        publishdate_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:NewsSentimentUntreated)
    }
    
    static {
      defaultInstance = new NewsSentimentUntreated(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:NewsSentimentUntreated)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_NewsSentimentUntreated_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NewsSentimentUntreated_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034NewsSentimentUntreated.proto\"\347\001\n\026NewsS" +
      "entimentUntreated\022\020\n\010newsCode\030\001 \002(\t\022\r\n\005t" +
      "itle\030\002 \001(\t\022\014\n\004text\030\003 \001(\t\022\020\n\010newsType\030\004 \001" +
      "(\t\022\022\n\ncompanyIds\030\005 \003(\t\022\024\n\014companyNames\030\006" +
      " \003(\t\022\023\n\013industryIds\030\007 \003(\t\022\025\n\rindustryNam" +
      "es\030\010 \003(\t\022\021\n\tentryDate\030\t \001(\t\022\016\n\006typeOf\030\n " +
      "\001(\t\022\023\n\013publishdate\030\013 \001(\tB-\n\021classify.pro" +
      "tobufB\030PbNewsSentimentUntreated"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_NewsSentimentUntreated_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_NewsSentimentUntreated_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_NewsSentimentUntreated_descriptor,
              new java.lang.String[] { "NewsCode", "Title", "Text", "NewsType", "CompanyIds", "CompanyNames", "IndustryIds", "IndustryNames", "EntryDate", "TypeOf", "Publishdate", },
              classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.class,
              classify.protobuf.PbNewsSentimentUntreated.NewsSentimentUntreated.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
